### ISSUE TITLE
Author's name a ORCID 'required' label are mis behaving 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1009]
The label 'required' appears twice for "name" and once for "ORCID", which is once too many time in both cases. 

This can be replicated by preparing submissin for both NIH and J10P. validation behavior seems unaffected.

<img width="892" alt="Screen Shot 2019-07-29 at 12 08 15 AM" src="https://user-images.githubusercontent.com/11050142/62056004-b5149780-b1ea-11e9-8c93-e94e1852d839.png">

**Comment by jabrah** [comment]
The reason why this wasn't caught before is that for some reason, the extra `(required)` labels do not appear when going through the workflow with no DOI. Perhaps Alpaca treats these fields differently when data is pre-populated.

I have recreated this behavior when pre-populating author data from a DOI

**Comment by jabrah** [comment]
In this case we have a rendered schema that looks like:

``` javascript
{
  "data": {
    "authors": [
      { "author": "Moo Jones", "orcid": "1234j" },
      { "author": "Moo Jones Jr" }
    ]
  },
  "schema": {
    "properties": {
      "authors": {
        "type": "array",
        "items": {
          "properties": {
            "author": {...}
            "orcid": {...}
          },
          "required": ["author"]
        }
      }
    },
    "required": ["author"]
  }
}
```

When this form is rendered and _then_ we add a new entry as a user, the author name is rendered with a single `(required)` label and the author orcid does not have the `(required)` label, as we want. However, when alpaca is given the `"data"` property to render pre-populated authors, it decides to add an extra required label on each of the child properties

**Comment by jabrah** [comment]
I have a pretty gnarly workaround.

Since this _seems_ to only appear when pre-populating data into array fields, we can be sure that data actually exists for these fields. These pre-populated array fields will then _always_ satisfy the presence requirement. So it will still be valid if we remove the requirement for only the rendering schema.

On initial testing, this seems to do the trick. Now to add some automated tests...
