### ISSUE TITLE
Investigate an approach to enable maintaining multiple brands for PASS UI

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1011]
As part of implementing harvard pilot, we need to figure out how PASS UI can be refactor in way to allow us to easy build ui images for diffeerent brands (JHU and Harvard)

**Comment by jabrah** [comment]
The doc has a section that looks a bit into this issue
https://docs.google.com/document/d/1ZLNtshgOO0hHttDDmhN5t2EnsE2x6Vrq5MIJL8up4gY/edit?usp=sharing
