### ISSUE TITLE
Address security vulnerability alerts

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1012]
Please review this list of detected vulnerabilities and address as many as possible during this time on PASS this week and next week. 
https://github.com/OA-PASS/pass-ember/network/alerts

**Comment by jabrah** [comment]
Please keep in mind that jQuery version 3.4.0 and 3.4.1 will break Alpaca. A fix for the bug causing this _may_ make it into jQuery 3.4.2, but this version is not released yet and has no ETA

**Comment by markpatton** [comment]
Must also update the ember-fedora-adapter for security issues at the same time.
