### ISSUE TITLE
Apply Harvard Branding  and UI elements to PASS UI

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1013]
Apply Harvard branding to PASS UI in accordance with this branding guide https://library.harvard.edu/brand-guidelines

Images to be used for header can be found here https://drive.google.com/open?id=1tg6XUE1xZOFDpM_SuywFtdI_VPe1ehKh or contact hanh if you have access issue. 

Logos to be used on the site https://drive.google.com/open?id=1OPhphs9OOpIZ7-4tcR6TqPgd3SmTttr9

**Comment by jabrah** [comment]
Temporarily located in a new branch:
https://github.com/OA-PASS/pass-ui-static/tree/feature/branding-harvard-trial

This can be used in `pass-docker` by changing the `STATIC_HTML_GIT_BRANCH` in `.env` and giving `static-html` a different tag in `docker-compose.yml`. Then, when you use `docker-compose build static-html`, the new image will be built and can be run in the PASS stack

**Comment by jabrah** [comment]
Minimal styling so far:

![Screenshot from 2019-08-16 14-36-51](https://user-images.githubusercontent.com/5167587/63190056-5f861a80-c033-11e9-8734-5593794dc821.png)

**Comment by jabrah** [comment]
We can now see harvard branding and data in the `pass-ember` dev environment when running this command from the `.docker/` directory

```
docker-compose -f harvard.yml up -d ...
```
