### ISSUE TITLE
Research and decisions around which API to use in looking up OA copies based on DOI

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1064]
We have discussed the use of two different API’s (unpaywall and open access button) for retrieving manuscripts which may be related to a provided DOI. There’s been some discussion around how the shape of the data looks from both API’s but there’s not been a decision yet as to which API to use (or if we’ll try to accommodate both). So there is a bit more discussion necessary.

**Comment by jabrah** [comment]
Seems we've decided to focus on integrating only Unpaywall for an initial release. We could potentially add OpenAccessButton at a later time
