### ISSUE TITLE
Add the behavior that allows streaming of remote file for uploading

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1066]
This involves streaming a file into client side memory via one of several methods that have not yet been tested. It’s very likely that this is possible without much issue, but given it’s a new operation that we’ve not used there is a non-zero chance that stumbling blocks in this part of the service would require us to re-envision this as a backend service or that it might just take a bit more effort.

This also involves creating the ui elements which enables the rendering and selection of OA copies returned by OAB/UPW api. see this slide deck for suggestions of lay out https://docs.google.com/presentation/d/1zgcXbT49dgePmWxKvx8XUKQc-OlgUD8NIO2UyiblTnI/edit#slide=id.p

**Comment by jabrah** [comment]
External file handling now moved to external service https://docs.google.com/document/d/1HukpuDOzyT9s2j8QN5TcNu95O985_QmJSGnjqBJi53k/edit?usp=sharing
