### ISSUE TITLE
COVID banner text and associated FAQ entry

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1071]
<img width="1174" alt="Screen Shot 2020-05-01 at 10 44 47 AM" src="https://user-images.githubusercontent.com/11050142/80813982-0ea25c00-8b99-11ea-9218-8fe5985cb5a6.png">

- [x]  We're not supporting data deposit, so we need to remove the "and data" from the banner text. 
- (will not address) When banner is clicked from the home page, can users be taken directly to the first step of the workflow with the COVID checkbox already checked?
- [x] update faq entry

**Comment by jaredgalanis** [comment]
@htpvu clicking the banner on the home page should take the user to the workflow with the box checked. It was in the pass-ember dev env. I'll have to follow up on that.

**Comment by htpvu** [comment]
Consider the need for a new backend service to support OAB integration. We can park the investigation into where user is taken when the banner is clicked. 

Still need to remove "and data" from banner text.

**Comment by htpvu** [comment]
Please use the default text for FAQ as written in this slide https://docs.google.com/presentation/d/1zgcXbT49dgePmWxKvx8XUKQc-OlgUD8NIO2UyiblTnI/edit#slide=id.g73c745cd41_0_74. 

I'll create a new ticket if/when the text from the OSC comes in
