### ISSUE TITLE
prompts on file upload steps should properly reflect the situation when OA Copies aren't found

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1078]
When there is no OA copies found, the prompt doesn't read right. We need to either change that prompt to not mention any OA copies, if no OA copies are found OR we need to add some text about OA copies not being found

<img width="1158" alt="Screen Shot 2020-05-12 at 10 33 53 AM" src="https://user-images.githubusercontent.com/11050142/81712938-39b36800-9443-11ea-8d7c-0640524ca1bf.png">

**Comment by jabrah** [comment]
![image](https://user-images.githubusercontent.com/5167587/81717300-5e5e0e80-9448-11ea-9a8a-2853a6d58197.png)
