### ISSUE TITLE
Indicate a manuscript was submitted as a COVID manuscript in the submission details page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1079]
Currently the submission details page shows no indicator that a manuscript was submitted as a COVID manucript into JScholarship. 

Please propose/suggest some visual cue to this, run it by me (hanh) before implementation.

Thanks.
<img width="1157" alt="Screen Shot 2020-05-12 at 10 45 29 AM" src="https://user-images.githubusercontent.com/11050142/81714504-22757a00-9445-11ea-9879-e6b971319cf7.png">

**Comment by jabrah** [comment]
Proposal, needs some feedback:

![image](https://user-images.githubusercontent.com/5167587/81726388-4a6cd980-9455-11ea-82f1-194a7bdfed12.png)
