### ISSUE TITLE
Update message on File upload step of the workflow

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#1085]
In the file upload step, in the case of download service not able to download a manuscript automatically, but use has the ability to download the manuscripts his/herself in order to attach to the submissions, update the message to encourage user to perform his/her own file download in order to attach Open Access manuscript to the submissions.

**Comment by htpvu** [comment]
current message being referred to. 
![](https://files.slack.com/files-pri/T03AE3ML1-F014N941CGN/screen_shot_2020-06-04_at_12.15.31_pm.png)

**Comment by jaredgalanis** [comment]
Closing as we addressed this in https://github.com/OA-PASS/pass-ember/pull/1088
