### ISSUE TITLE
Submission workflow sub-nav tabs don't work in Step 3

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#1093]
![image](https://user-images.githubusercontent.com/5167587/89910787-a6fba400-dbbe-11ea-9a38-439cbc9abba9.png)

In all other steps, you can jump around the workflow as expected using these tab buttons, however when you are sitting on the 3rd step (Policies), you cannot use these tab buttons to navigate away. The "Next" and "Back" buttons work, though

**Comment by jaredgalanis** [comment]
addressed by https://github.com/OA-PASS/pass-ember/pull/1082/commits/ef3807f67896c60666bf7ece904b556363445393
