### ISSUE TITLE
Ember dev container fails to run

### ISSUE THREAD

**Issue by markpatton** [OA-PASS/pass-ember#1108]
When the ember dev container tries to run:
 
```
node-sass@4.14.1 postinstall /app/node_modules/node-sass
> node scripts/build.js

Binary found at /app/node_modules/node-sass/vendor/linux_musl-x64-57/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2398 packages in 41.492s
/app/node_modules/ember-cli/node_modules/find-up/node_modules/locate-path/index.js:41
		} catch {
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/ember-cli/node_modules/find-up/index.js:3:20)
```

**Comment by aforward** [comment]
Note that my original question was `What version of NODE / NPM are you using` (to avoid that being an issue, but this issue was equally observed by @markpatton when starting up a new development environment so it might be more wide-spread due to a dropping of support for node-sass (note that in an unrelated project I observed a similar problem and had to change my dependency to `sass` altogether)

Here are the steps

1. Remove all node dependencies
2. Run `npm install`
3. Observe the failure below

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.14.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.14.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by derekbelrose** [comment]
Hey @aforward I tested this on an Ubuntu 21.04 LXC container with the following results:
```
ubuntu@my-ubuntu:~/pass-ember$ node_modules/ember-cli/bin/ember build
DEPRECATION: The integration of jQuery into Ember has been deprecated and will be removed with Ember 4.0. You can either opt-out of using jQuery, or install the `@ember/jquery` addon to provide the jQuery integration. Please consult the deprecation guide for further details: https://emberjs.com/deprecations/v3.x#toc_jquery-apis
Environment: development
cleaning up...
Built project successfully. Stored in "dist/".
ubuntu@my-ubuntu:~/pass-ember$ npm --version
7.5.2
ubuntu@my-ubuntu:~/pass-ember$ 
```

The version of `npm` that comes in the Ubuntu repositories should be able to handle this.  I was able to run `npm install` as a non-root user without the use of `sudo`.  What distribution are you trying to run this on?

**Comment by markpatton** [comment]
So the failure was coming trying to build the ember development container which just installs ember, then the app, and runs it with ember server. In order to test try to build the container described by ember-dev/Dockerfile. Failures should be cross platform most of the time. But for the record the failure happens for me when trying to build on the container on Fedora 34. I just tried again and the problem still exists. I suspect just updating a few dependencies will fix it, but I won't be able to spend time trying until Friday.

**Comment by derekbelrose** [comment]
@markpatton arecyiu asking me to try building it a different way?

**Comment by markpatton** [comment]
Interesting that I notice differential behavior using npm install vs yarn install locally, but when I change the dev container between yarn and npm I get exactly the same failure.

**Comment by markpatton** [comment]
Ok. The failure is actually caused by trying to install ember, not be trying to install the app. So this line in the Dockerfile is failing:
```
RUN yarn --verbose global add ember-cli
```

**Comment by markpatton** [comment]
Ok. Rebuilding the ember-dev container allows pass-ember to actually start. This is because rebuilding the container means grabbing a new version of ember-cli with various updates.

The site starts, but when you attempt to login, there is an error
```
e.hbs
loc$$1.sliceStartChars is not a function
```
There is a related error message when "yarn install" is run on the app by the container. Likely updating the ember-cli version also means that some dependencies need an update.
