### ISSUE TITLE
Change dashboard layout

### ISSUE THREAD

**Issue by cameronblandford** [OA-PASS/pass-ember#133]
What Happens:
* As a user, when landing on the site, I'm directed to a verbose page that requires a second click to get anywhere, and the places it links are already in the nav.

What Should Happen:
* Put useful information on this page, e.g. submissions and grants associated with me, stats about submissions

**Comment by karenhanson** [comment]
@htpvu We have added some information, but it seems that this might be best addressed through separate tickets to add specific functionality. Proposing we close this.
