### ISSUE TITLE
Mobile-friendly table views

### ISSUE THREAD

**Issue by cameronblandford** [OA-PASS/pass-ember#134]
This ticket is in development - we're currently looking at [Ember Light-Table](https://offirgolan.github.io/ember-light-table) as a possible solution.

What Happens:
When I view a model table on mobile, it breaks the layout and is hard to read. 

Example:
![alt text](https://image.ibb.co/mRVbuc/123123123123123.png)

What Should Happen:
The table should be responsive and adapt to mobile view.

Also:
* Pagination shouldn't be shown if there are no pages.
* "Items per page" dropdown should be more clear as to what it does - needs clarifying text and better positioning.
* Search bar shouldn't need an X button to clear it.
* "Search:" word should be _inside_ search bar.

**Comment by htpvu** [comment]
If this is some that is easy to address (reads take little time), i think it'd be great to pursue. But mobile friendliness is not a core requirements for us. I'd rather us to spend a huge a mount of time on  mobile friendliness specifically. Could you let me know if it takes more than a day of work for it?

**Comment by cameronblandford** [comment]
This probably won't be getting done any time soon. Closing the issue.
