### ISSUE TITLE
Outline logic + behavior for submission workflow

### ISSUE THREAD

**Issue by cameronblandford** [OA-PASS/pass-ember#136]
This is a ticket to better spec out the submission workflow and make more tickets for it.

**Comment by Rytiggy** [comment]
- Metadata page shows blank if you haven't selected anything or entered any info
  - add logic to not allow blank pages. Required fields
 
![image](https://user-images.githubusercontent.com/17414914/37779024-c32b804e-2dc1-11e8-9d64-82951db5c2a3.png)

**Comment by jabrah** [comment]
Repositories page may not populate properly unless the user first goes through the Policies page, and clicks "Save and Continue" or whatever to progress.

**Comment by htpvu** [comment]
It's probably a good idea not to let users progress any further in the workflow if their choices thus far resulted in no target repositories. 

By default, JHU JScholarship is selected as a target repo --> in this case the common metadata should be collection. But if for some reason, user wasn't required to submit it to NIHMS, and he/she opt out of depositing into JScholarship, then he/she should probably be asked to exit the workflow OR taken out of the workflow, whichever seems like a nicer experience.

**Comment by htpvu** [comment]
I think you guys mentioned it already, but in case it get missed: we need to handle error more gracefully.  in fact, I dont think we deal with exceptions and errors at all in the workflow currently. A helpful error page is a start. Maybe better state management so users dont have to restart and re enter data after an exception.
