### ISSUE TITLE
PI value on Grant Detail table still has "loading... " value

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#178]
<img width="991" alt="screen shot 2018-04-26 at 8 48 05 pm" src="https://user-images.githubusercontent.com/11050142/39338801-25d28dea-4993-11e8-8678-9249e86504ee.png">

**Comment by Rytiggy** [comment]
Should be solved now

**Comment by htpvu** [comment]
will wait to see behavior once user service is integrated.
