### ISSUE TITLE
Column sort is not working on Submissions table 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#181]
rev. bf0d3853

**Comment by Rytiggy** [comment]
As it stands right now there is sorting on the submission table. Could you elaborate more on what you mean?
![giphy](https://user-images.githubusercontent.com/17414914/39363728-52def7f4-49f9-11e8-990e-f62bca14f9bb.gif)

**Comment by jabrah** [comment]
I am getting some odd behavior with the Submissions table as well: the column sort works with the status and two date columns, but does not work for article, corr author, and repo columns. I get the same behavior with the table in Grant Details

**Comment by cameronblandford** [comment]
This is related to https://github.com/OA-PASS/pass-ember/issues/253 - ember-models-table doesn't seem to support sorting or filtering by fields from related models. I'll look into this and see if there's a way around it. If there is, it should fix both problems.

**Comment by jabrah** [comment]
http://onechiporenko.github.io/ember-models-table/v.2/#/examples/sort-by-filter-by

I played around a tiny bit, but couldn't get things to work. We might have to define a separate model for the table to use, independent of the Ember models. Perhaps something as naive as this? Then `ember-models-table` should have easy keys to sort and filter by?

``` javascript
let tableModel = [];
submissions.forEach(sub => {
  tableModel.push({
    title: sub.publication.title,
    repo: sub.repositories.map(repo => repo.get('name')).join(', '),
    ...
  });
});
```

**Comment by cameronblandford** [comment]
This looks like a decent approach to me - I imagine we'd still have to turn them into ember models though, because ember-models-table expects ember models, and probably as such uses things like `.get()` which normal POJOs don't have access to.

**Comment by htpvu** [comment]
verified on rev. 1f687411
