### ISSUE TITLE
Need to relayout the authors contact information in the common metadata form

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#182]
Need to allow for displaying of multiple authors, their sequence, their email address.
<img width="925" alt="screen shot 2018-04-26 at 8 56 58 pm" src="https://user-images.githubusercontent.com/11050142/39339013-670e631e-4994-11e8-84bf-fe7be4a5270b.png">

**Comment by cameronblandford** [comment]
See "Form with Add Item Button" section of [this alpaca doc page](http://www.alpacajs.org/docs/api/forms.html).

**Comment by Rytiggy** [comment]
PR for adding multiple authors https://github.com/OA-PASS/pass-ember/pull/202

**Comment by htpvu** [comment]
Discussed changes needed for authors' names an associated information with @Rytiggy offline. 
The following items needs to be addressed

- [ ] We dont display affiliation information on the UI, but will capture it in the model
- [ ] We dont capture/display email addresses
- [ ] We capture and display ORCiDs as available and tie each of them to the associate author

**Comment by htpvu** [comment]
Author's name and associated ORCiD should be in two textboxes that are side-by-side. 
<img width="1104" alt="screen shot 2018-05-06 at 10 25 10 pm" src="https://user-images.githubusercontent.com/11050142/39682230-b8238c44-517c-11e8-8179-3bc5a458bb43.png">

**Comment by Rytiggy** [comment]
@htpvu make sure you restart docker and have the latest develop. I'm pretty sure that other than the side by side that this is solved. Ill address the side by side in a PR soon.

**Comment by htpvu** [comment]
ok let me try

**Comment by htpvu** [comment]
can we remove "author" from the author name/orcid group? 
![screen shot 2018-05-07 at 12 54 05 pm](https://user-images.githubusercontent.com/11050142/39713773-fa387e86-51f5-11e8-87ee-cf3150c15abd.png)

**Comment by htpvu** [comment]
@Rytiggy i removed the needs review tag, to mark that it still needs at least some discussion, if not work. 

Besides the removal of repeated "author" label, i also don't love the +/- sign on every single entry. Please talk to me when you workon this ticket so we can discussion option.

**Comment by Rytiggy** [comment]
In talking with @htpvu we have decided to make the authors display more compact. Remove the title Name and ORCID from each row and only leave them on the top one. Remove all extra white space between authors.

**Comment by Rytiggy** [comment]
This is now a duplicate ticket https://github.com/OA-PASS/pass-ember/issues/303
