### ISSUE TITLE
OAP Repo Id column in submissions table shows no data

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#185]
Linked to `deposit.repositoryCopy.externalIds` which should have test data, but nothing is displayed. Occurs in submissions table and grant details submissions table

**Comment by htpvu** [comment]
We have descoped the ability to email corresponding author. therefore, i think it's better that we remove the Corr. Authos column altogether.

**Comment by htpvu** [comment]
I'd like to talk about how the value in parentheses for the OAP repo id is obtained. Please ping me.

**Comment by htpvu** [comment]
verified on rev. 1f687411
