### ISSUE TITLE
Authors name not displaying correctly in the review page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#192]
It seems that the author's firstname is displayed in one field, while authors lastname is on adifferent displaying field
<img width="226" alt="screen shot 2018-04-27 at 10 08 52 am" src="https://user-images.githubusercontent.com/11050142/39367823-dd905666-4a05-11e8-97ec-694ec9471a61.png">

**Comment by cameronblandford** [comment]
This is a side-effect of the method we're using to display that data dynamically. What we could do is make it clear what those fields are by changing their names to "author first name" and "author last name". Would that work?

**Comment by Rytiggy** [comment]
![image](https://user-images.githubusercontent.com/17414914/39484959-5672a3e4-4d45-11e8-8eeb-847b13a0593b.png)
PR for authors name not displaying correctly  https://github.com/OA-PASS/pass-ember/pull/202

**Comment by htpvu** [comment]
@Rytiggy this should be "author(s)" to deal with the case of multiple authors, which is a common case.
