### ISSUE TITLE
Produce a complete stream/string of Submission Metadata blob

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#194]
the produced metadata blob should represent a complete metadata for Submission records with no missing field - this is to inform deposit service on what to expect.

**Comment by cameronblandford** [comment]
> with no missing field

Do you mean you'd rather see, for example, `myField: null` than nothing at all? Or do you mean that everything needs to be filled out by the user/autofill?

**Comment by htpvu** [comment]
for real data, I think omitting empty field is fine, but i'm looking for a sample submission metadata blob so i can give the Deposit service people to help them with coding the parser for such blob.

**Comment by htpvu** [comment]
thanks.

**Comment by htpvu** [comment]
@Rytiggy 

i talked to Elliot (who's working on the deposit service) he had some feedback on how the metadata is organized that i thought was logical. he thinks that the publication cross ref related metadata should all be in common section. that would mean ISSN and embargo information goes into "common" section. leaving deposit agreement in "JScholarship" and NLMTA_ID in "nih"

Can we make this change and produce a new blob? ping me if you have concern?

**Comment by htpvu** [comment]
i would like the embargo related stuff to be on the common page.

**Comment by htpvu** [comment]
got it. thanks.
