### ISSUE TITLE
Consider changing up the font for readability

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#200]
Feedback from sayeed (and I) is the current font used is hard to read (too small, not enough contrast). Can we change this up in ways that still conform to the style guide, but is easier to read.

**Comment by Rytiggy** [comment]
## Todo to improve readability
- Increase fontsize to 16px for body text elements 
- Adjust text colors for better contrast
- Change title font to Arnhem Pro
- Better postion logo

**Comment by Rytiggy** [comment]
https://github.com/OA-PASS/pass-ember/pull/201

**Comment by htpvu** [comment]
@Rytiggy is the blue used for hyperlink the darkest blue yet? it's still pretty hard on the eyes for lack of contrast with white background.

**Comment by Rytiggy** [comment]
@htpvu This should be more readable now. 
https://github.com/OA-PASS/pass-ember/pull/224

![image](https://user-images.githubusercontent.com/17414914/39596601-e1bd3e86-4ee0-11e8-8b8f-fc63b34d2045.png)

**Comment by htpvu** [comment]
looks good.
