### ISSUE TITLE
Update PASS UI based on Branding review feedback

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#209]
- Change to use JH enterprise logo
- Change heading font to Quodan
- Remove "Johns Hopkins University" from the header image
- Change "Public Access Submission System" on the top banner to "PASS" using Quodan font.

**Comment by Rytiggy** [comment]
#### These should cover the above requests: 
- Merged already: https://github.com/OA-PASS/pass-ember/pull/207
- awaiting to be merged: https://github.com/OA-PASS/pass-ember/pull/210

**Comment by htpvu** [comment]
@Rytiggy could you use one of the logo files here for the CDC logo? https://commons.wikimedia.org/wiki/File:US_CDC_logo.svg

**Comment by Rytiggy** [comment]
![localhost_4200_welcome 1](https://user-images.githubusercontent.com/17414914/39579526-04f4cf9e-4eb5-11e8-8b3e-c6a1ae6634ff.png)

What are you thoughts on the JHU logo, Im thinking we should find one with more substance?

**Comment by htpvu** [comment]
@Rytiggy just now see your message. I dont get notifications!!! i'll have to figur eout how to get notifications. anyways, let me see aboue a different logo i think there's a few styles. I'll get back to you.

**Comment by Rytiggy** [comment]
@htpvu  test

**Comment by htpvu** [comment]
look good.
