### ISSUE TITLE
Remove outdated references between objects that are not present in Pass data model

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#222]
Now that Elasticsearch and Fedora are integrated into the Ember app, we should be able to remove extra references on model objects that are not present in the current PASS data model (https://github.com/OA-PASS/pass-data-model)

* [x] `grant.submissions` reference, pointing to submissions tied to a particular grant
* [x] `publication.submissions`
* [x] `funder.repository`
* [x] `publisher.journals`
* [x] `repository.policy` `repository.submissions`
* [x] `submission`
  * [x] `submission.deposits`
  * [x] `submission.files`
  * ~~`submission.filesTemp` : is this going to be spiked by the strict-checking adapter?~~
* [x] `user.submissionDraft` doesn't look like it is used anymore

**Comment by jabrah** [comment]
Currently working off https://github.com/jabrah/pass-ember/tree/dev/remove-non-model-references

**Comment by cameronblandford** [comment]
Verifying that `user.submissionDraft` is obsolete and not being used currently.

**Comment by jabrah** [comment]
Note: `submission.filesTemp` will be removed in a future PR

**Comment by htpvu** [comment]
I dont think I have a good way to verify this without diving into the code. So someone else should verify and close this ticket, @jabrah ? If there are UI symptoms of this tickets, let me know, i can verify it then.

**Comment by htpvu** [comment]
test data seems to load fine on rev. 08931c7c
