### ISSUE TITLE
PI field is missing values in the Grant table. 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#226]
<img width="1171" alt="screen shot 2018-05-03 at 2 52 49 pm" src="https://user-images.githubusercontent.com/11050142/39596869-ba625c6c-4ee1-11e8-8d70-38cccabe6477.png">

**Comment by jabrah** [comment]
This should be addressed when we have a user service integrated. We currently have this mocked with Mirage which is intercepting all `user` requests, so none of the user data is being saved in Fedora. Once we can eliminate this mocking, this should start working again.

**Comment by htpvu** [comment]
an issue with mocked test data
