### ISSUE TITLE
Submit button is unresponsive

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#229]
On rev. 8c5e3591 

<img width="1151" alt="screen shot 2018-05-03 at 3 35 00 pm" src="https://user-images.githubusercontent.com/11050142/39598925-27ebebb2-4ee8-11e8-8705-e160f005f9a2.png">

**Comment by cameronblandford** [comment]
This might be an issue with the fedora-adapter. Talking to Mark about it now.

**Comment by jabrah** [comment]
So when the final **Submit** button is clicked, we do get an error message from the `ember-fedora-adapter` complaining that it can't serialize an attribute with type `[object Object]` or something along these lines. This suggests that a part of the Submission object does not match with our JSON-LD context.

It looks like there is data about uploaded files on the Submission object which looks like it would trip up the adapter. 

`workflow-files.js` will need to be updated to create `File` model objects

**Comment by htpvu** [comment]
Great!
