### ISSUE TITLE
Update review page to deal with weblink repository (such as ERIC)

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#232]
- [ ] Add a section titled "External submission portal ". In it, display text saying "Please visit the following web portal to submit your manuscript directly. Metadata displayed above could be used to aid your submission progress." Below that add a bulleted list with hyper-linked ERIC in it. \
- [ ] Remove the grey box at the verify bottom asking users to verify their action. 

<img width="1149" alt="screen shot 2018-05-03 at 3 49 20 pm" src="https://user-images.githubusercontent.com/11050142/39599362-a3566826-4ee9-11e8-9445-5988cfd19a59.png">

**Comment by cameronblandford** [comment]
This is a duplicate of https://github.com/OA-PASS/pass-ember/issues/140

**Comment by htpvu** [comment]
verified.
