### ISSUE TITLE
Journal names need to support auto complete when users are typing journal name in

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#234]
also need so retain the typed in journal name, currently it gets cleared off.

**Comment by cameronblandford** [comment]
@htpvu neither of these happen on my copy of develop. Can you elaborate on what you did, what you expected to happen, and what happened, so I can try to reproduce the error?

**Comment by htpvu** [comment]
I didn't give the application a DOI, i just started to type in a Title and Journal Name. One of our usecases is the submission of some publication with out DOI, so users need all the help they can get from the application to fill out information.

**Comment by Rytiggy** [comment]
@htpvu, @cameronblandford and I have tested this and this issue seems to be solved now. moving this to done awaiting review.

**Comment by htpvu** [comment]
verified rev. d3c7797f
