### ISSUE TITLE
on Jscholarship metadata page, if the embargo checkbox is checked, Embargo enddate is a required field. 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#242]
OTherwise, it is not

**Comment by cameronblandford** [comment]
There's an example on how to do interdependent field validation [here](http://www.alpacajs.org/docs/api/validation.html) in the alpaca docs

**Comment by Rytiggy** [comment]
For this issue, I will also address moving the title and journal titles out of NIH and on to the COMMON schema.

**Comment by htpvu** [comment]
verified on rev #d3c7797f
