### ISSUE TITLE
Remove notification icon from page, since we're not notifying anything. 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#244]
<img width="336" alt="screen shot 2018-05-04 at 12 34 52 pm" src="https://user-images.githubusercontent.com/11050142/39640014-a719f064-4f97-11e8-94ae-681a6694c61d.png">

**Comment by htpvu** [comment]
The user name and icon got moved to the left.

<img width="1187" alt="screen shot 2018-05-06 at 9 41 07 pm" src="https://user-images.githubusercontent.com/11050142/39681158-4222ad82-5176-11e8-98e5-157ba21dd44e.png">

**Comment by Rytiggy** [comment]
I have this fixed in this PR https://github.com/OA-PASS/pass-ember/pull/255  👍

**Comment by htpvu** [comment]
looks good.
