### ISSUE TITLE
Add acceptance tests

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#245]
- [x] Add mirage testing environment
- [x] Write sample login test
- [ ] Outline required tests
- [ ] Write those tests

**Comment by cameronblandford** [comment]
## Required Tests

- [ ] User can make a submission and see it in a table
- [ ] User can see every column populated in the submissions table
- [ ] User can see every column populated in the grants table
- [ ] User can see every field populated in the submissions detail page
- [ ] User can see every field populated in the grants detail page

**Comment by htpvu** [comment]
Close to be address more specifically in new tickets.
