### ISSUE TITLE
Improve user feedback [WIP]

### ISSUE THREAD

**Issue by cameronblandford** [OA-PASS/pass-ember#249]
## What

Users need confirmation that what they've done has properly propagated through the system.

## Why

It greatly improves the user experience, and makes debugging easier. Pretty standard fare.

### Toasts

* When the client gets confirmation that a change has propagated to the server
* When an error occurs

### Colored buttons, text

* Statuses should have colored backgrounds (or a colored dot next to them)

**Comment by htpvu** [comment]
I think much of this has been done. Further requirements for improvement will/should be recorded in specific ticket
