### ISSUE TITLE
Improve usage instructions 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#252]
Better label verbiage and placement.

- direction/instruction about required or optional fields need to be inline (next to the field name or as suggestion text in the text boxes)
- Rename categories of repository from "Required" to "Funders' repositories", from "Local" to "Local repositories
- Add text to explain which version of the publication should be submitted inthe "files" page - text to be provided by Hanh

**Comment by htpvu** [comment]
To explain which version of the publication is to be submitted:
On the follow up page (file upload)

WHEN a submission to NIHMS is detected: Above `Attach manuscript/article files to this submission.` , add the following paragraph:

> NIH and other PMC-supported funding agencies {https://www.ncbi.nlm.nih.gov/pmc/about/public-access/} require funded authors to submit the Author's Accepted Manuscripts. For clarification on the difference between Author's Accepted Manuscript and Final Published  Article, please see here {https://www.ncbi.nlm.nih.gov/pmc/about/authorms/}.

> To ensure successful processing of your submission in NIHMS, be sure to include all referenced tables, figures and supplemental files in your submission, in addition to the Author's Accepted Manuscript. 

<img width="1024" alt="screen shot 2018-05-21 at 10 08 04 pm" src="https://user-images.githubusercontent.com/11050142/40338581-dca34ad2-5d43-11e8-9347-140bbe515258.png">

**Comment by Rytiggy** [comment]
Reopened waiting for Hanh to review, this ticket got closed accidentally

**Comment by htpvu** [comment]
verified on rev. 5fbc7bc6
