### ISSUE TITLE
Integrate with real user service

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#258]
I'm not sure what all this will entail both in the back and and the front end. So part of this card will involve figuring that out. 

This will requires : 
- mock impl of the userProvider
- add user service to the infrastructure
- some rerouting of requests?

**Comment by Rytiggy** [comment]
This issue is blocking this issue https://github.com/OA-PASS/pass-ember/issues/226

**Comment by htpvu** [comment]
DONE!
