### ISSUE TITLE
Use the search service autocomplete service for journals

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#279]
Initial implementation of autocomplete in Elasticsearch should be ready to integrate into the PASS UI https://github.com/OA-PASS/pass-indexer#auto-completion-suggestion-support

**Comment by jabrah** [comment]
Current autocomplete implementation will only make suggestions with the user input as the prefix for an entire field. Example:

> User types `eng`, attempting to find `Advances in Engineering Education`. Autocomplete returns no results.
> User types in `adv`, `Advances in Engineering Education` now appears

**Comment by htpvu** [comment]
To be reviewed with real data.

**Comment by jabrah** [comment]
Autocomplete has been permanently removed for Grants, and temporarily been removed for Journals - pending updated `assets` container

**Comment by jabrah** [comment]
This ticket was modified when the journal data was incomplete, which has since been addressed. I think this ticket was simply overlooked and should be reviewed and closed

**Comment by karenhanson** [comment]
verified in 566f344, but related ticket #521 still needs work.
