### ISSUE TITLE
Search integration needs an efficiency pass

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#280]
Current implementation of `Store.query` in the UI is very inefficient, resulting in many search requests for some pages. In some of these cases, the multiple search requests can be consolidated into a single search request that is then parsed by the UI.

Non exhaustive list of places to investigate:
* `grants.index`
* `submissions.index`
* `grant.detail` when populating the associated submissions table

**Comment by cameronblandford** [comment]
@jabrah what's the status of this ticket?

**Comment by jabrah** [comment]
Things could be optimized further, but I think it is in an OK state
