### ISSUE TITLE
Separate public landing pages from Ember application

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#284]
public page include:

- landing splash page
- about page
- contact page

@cameronblandford what urls can these pages have?

**Comment by cameronblandford** [comment]
@htpvu these should probably either be stored on a separate endpoint, like static.pass.jhu.edu/<landing/contact/about> or s.pass.jhu.edu, or their own dedicated route that nginx would intercept, like pass.jhu.edu/public/<page>. Either option would work fine, and that implementation would be left up to the person deploying it

**Comment by Rytiggy** [comment]
I have set this up to be hosted on a temporary GitHub pages site. https://rytiggy.github.io/pass-ui-static/index.html. Once we figure out our domains we will be hosting on, we can move it there.

**Comment by htpvu** [comment]
i'm going to leave this open until we have a new docker image for the ui that contain both the ember app and the separated out static site in the `pass-docker` env and the cloud env.

**Comment by Rytiggy** [comment]
We need to update the static pages to be inline with the ember app
