### ISSUE TITLE
Jscholarship appears 3 times on repositories page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#286]
Note the rev # on the screenshot.
steps to reproduce:
1. start a new submission workflow from the dashboard, use a method b DOI to add metadata, select an NIH grant. 
2. hit keyboard back button (i did accidentally) this will exit the workflow back to the dashboard
3. start a new submission again, using the same DOI, this time select an education grant. step through to the repositories page
4. the below image happened.
<img width="1178" alt="screen shot 2018-05-09 at 9 21 00 pm" src="https://user-images.githubusercontent.com/11050142/39847315-f1f3531a-53ce-11e8-976f-a6a51e267f4a.png">

**Comment by htpvu** [comment]
I have exited and return to new submission many times, each time i start a new submission jscholarship is being added 3 times.

**Comment by htpvu** [comment]
@cameronblandford is this the "unticketed issue" referred to in PR #288?

**Comment by cameronblandford** [comment]
It is - didn't see this ticket until after I wrote my PR.

**Comment by htpvu** [comment]
even though jscholarship only shows up once in the repositories page. it shows up twice in the reivew page. i did the golden path. no back and forth
<img width="877" alt="screen shot 2018-05-10 at 9 27 41 pm" src="https://user-images.githubusercontent.com/11050142/39901883-2b4416fc-5499-11e8-9cbd-786b6630210a.png">
