### ISSUE TITLE
reduce the size of the agencies logos on the landing table. 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#289]
They are nice, but usability testing feedback suggest that they sort of take over the whole page (Being so big and sharp). HOpefully reducing their size will give some focus back to the text. 

if possible, may be reduce enough in size that we can put the 5th logo on the row.

**Comment by Rytiggy** [comment]
![screen shot 2018-05-23 at 9 07 55 am](https://user-images.githubusercontent.com/17414914/40426340-d010f6fe-5e68-11e8-85c9-9699678b2404.png)
