### ISSUE TITLE
Files associated to a submission doesn't show up in Submission review page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#316]
Do we have file uploading working yet? i think so, if i recall correctly. 

This is the view i get from looking at a submission i just created with 4 files in it. Note the revision number
<img width="1095" alt="screen shot 2018-05-14 at 10 01 25 pm" src="https://user-images.githubusercontent.com/11050142/40032544-948a224c-57c2-11e8-96a7-e304ab58cf2d.png">

**Comment by htpvu** [comment]
Ah, looks like the files ARE there and did eventually showed up. I guess it took a while for them to upload. or however there's some latency there. So this ticket can be resolved by providing some explaination text on the Submission Details page in cases where users go ther eto look bu the files aren't done uploading yet.

**Comment by cameronblandford** [comment]
This is an issue with the indexer - the search request is successfully being made on our end, but the indexer isn't returning anything. Tagging @emetsger @markpatton on this to see if either of them have any insight.

Here's the cURL request:
```
curl -X POST \
  http://localhost:9200/pass/_search \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate, br' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Authorization: Basic YWRtaW46bW9v' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 183' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'Cookie: gsScrollPos-463=0; gsScrollPos-191=; gsScrollPos-849=0; gsScrollPos-843=' \
  -H 'Host: localhost:9200' \
  -H 'Origin: http://localhost:4200' \
  -H 'Referer: http://localhost:4200/submissions/http:%2F%2Flocalhost:8080%2Ffcrepo%2Frest%2Fsubmissions%2Fb3%2F48%2F51%2Fee%2Fb34851ee-1b1e-4875-97f1-e31988cd3a28' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36' \
  -d '{"query":{"bool":{"must":{"term":{"submission":"http://localhost:8080/fcrepo/rest/submissions/b3/48/51/ee/b34851ee-1b1e-4875-97f1-e31988cd3a28"}},"filter":{"term":{"@type":"File"}}}}}
'
```

and here's the http request:
POST /pass/_search HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Basic YWRtaW46bW9v
Connection: keep-alive
Content-Length: 183
Content-Type: application/json; charset=UTF-8
Cookie: gsScrollPos-463=0; gsScrollPos-191=; gsScrollPos-849=0; gsScrollPos-843=
Host: localhost:9200
Origin: http://localhost:4200
Referer: http://localhost:4200/submissions/http:%2F%2Flocalhost:8080%2Ffcrepo%2Frest%2Fsubmissions%2Fb3%2F48%2F51%2Fee%2Fb34851ee-1b1e-4875-97f1-e31988cd3a28
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36
Cache-Control: no-cache

{"query":{"bool":{"must":{"term":{"submission":"http://localhost:8080/fcrepo/rest/submissions/b3/48/51/ee/b34851ee-1b1e-4875-97f1-e31988cd3a28"}},"filter":{"term":{"@type":"File"}}}}}

**Comment by markpatton** [comment]
@cameronblandford 

Check that submission object in fcrepo to make sure it has the submission attribute set.
Then check the indexer logs to see if the indexer is getting messages about that fedora object being created/modified.
Finally do a search to see if it is in the index like `curl http://localhost:9200/_search?pretty&q=@type:Submission&size=100`.

**Comment by emetsger** [comment]
@htpvu @cameronblandford @Rytiggy @markpatton sorry, I am just seeing this, I'm not sure I got notified by GH re this issue.  Is this something I ought to look at, at this point?

I don't know all of the constraints of Ember, but binary file resources ought to be children of an LDP container (i.e. child resources of a `Submission`, or wherever Ember is uploading them).  If Ember is able to issue a request to list the children of a container, no interaction with the index is needed.

If interacting with the index is the easiest thing to do, it's important for Ember to confirm that the expected number of files show up in the index.  That is, if a user uploads 5 files, and a search for those files only lists 4 files, then Ember ought wait to perform the submission until it can confirm that the 5th file is in the index.

All that said, if there's something I can look at and provide more feedback I'll be happy to.  As the ticket is a few days old (my bad!) let me know if I can help.
