### ISSUE TITLE
Update grant selection feature in submission workflow

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#322]
In Grant step of the workflow, populate the drop down with logged-in user's grants (on which he/she is the pi) - sort by award number.

**Comment by jabrah** [comment]
This will likely be rolled into a future update to Autocomplete (#279), as the updated `pass-indexer` should include the ability for the search service itself to do the filtering.

**Comment by htpvu** [comment]
I don't see this restriction happening. I'm still seeing all the grants - where I should only see 5.

On rev. dd4d6985

In fact, can we please make the drop down to be populated with user grant. so he/she can select from the drop down instead of having to search? that would will probably remove the need to use auto complete?

**Comment by jabrah** [comment]
whoops! sorry if I mislabeled this ticket. My intent was that this ticket needs verification in the unmerged PR (https://github.com/OA-PASS/pass-ember/pull/292) - so code is not yet in `develop`. Same label situation in #279

**Comment by htpvu** [comment]
this is done in a different ticket
