### ISSUE TITLE
Handle session expiration more gracefully.

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#345]
figure out a good strategy to deal with expires session

**Comment by cameronblandford** [comment]
@htpvu what behavior are you seeing right now?

**Comment by htpvu** [comment]
humm. i dont remember. Let's chat with Elliot. he experienced it and request this feature. let's talk to him after scrum

**Comment by htpvu** [comment]
I asked Elliot about the behavior, he doesn't remember what the UI behavior is currently, but he noted that requests to the backend from ember would get spiked. we need to either, continuously ping something in the backend to keep the session live, or detect the expiration of the session and inform users of it, giving them a chance to continue the session

**Comment by htpvu** [comment]
The current behavior when session time out, is that the pages would still load with assets missing. The desired behavior is that when the session times out at the time of some user triggered request, he/she be redirected to home page with a message about them being logged out.

**Comment by jabrah** [comment]
Notes for myself: When a Shib session is expired and a given request is denied access, it seems you get a 302 response. I can't seem to intercept this response to act on, instead it is automagically picked up and dumped in the `ember-fedora-adapter#normalizeResponse` function.
