### ISSUE TITLE
We shouldn't use Store.findAll in the app due to performance

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#348]
Upcoming Docker environment will include large data set. `Store.findAll` puts a large burden on both client and server, `Store.query` is a better alternative

**Comment by birkland** [comment]
Yes, when used against the real data, `findAll` requests burn through many tens of thousands of resources; it is simply not practical to use `findAll` for any purpose.  My poor laptop.  All usages must be eliminated!

**Comment by markpatton** [comment]
Right. The findAll implementation uses a included children get to fedora which is just not going to do well with thousands of children. The solution is to add pagination support to Fedora, modify findAll to use Elasticsearch, or just use Store.query which uses Elasticsearch.

The other issue of note is that the contract of findAll does not support pagination. This makes me think all usage of it should just be replaced by Store.query anyway.

**Comment by birkland** [comment]
@markpatton Yeah - even paginating `findAll` wouldn't really work. It's just a bad pattern that doesn't fit the use cases, but was fine and easy at the beginning when we had just a handful of test objects.

**Comment by htpvu** [comment]
PR for this issue seems to have been merged

**Comment by htpvu** [comment]
nope it wasn't :(
