### ISSUE TITLE
For every place where the UI blocks user from proceeding in the workflow...

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#352]
In form user of why they can't proceed. make required action more obvious: eg file selections, required fields, click on ED link

**Comment by htpvu** [comment]
I can see the warning on the files step. I would have like some inline warning, such as highlight the section where required user's input is missing. But i'm willing to go to user testing with the current method of warning. 

However, i can't tell if the warning is working on the submit step. Submit button is way in the bottom, I can't feel if the warning box only appears in the header, which is out of sight, so i can't see it, OR if the warning box didnt' show up at all. 

<img width="1164" alt="screen shot 2018-05-25 at 1 13 18 pm" src="https://user-images.githubusercontent.com/11050142/40557347-cd44bbb6-601d-11e8-826f-23abb0eeab20.png">

**Comment by htpvu** [comment]
as discussed, move popup modal about un-signed deposit agreement to the Jscholarship meadata table,

**Comment by htpvu** [comment]
@Rytiggy i think we need to talk more about the orange box in the review step warning about clicking on ERIC link, themessage is very vague

**Comment by htpvu** [comment]
on rev. 9792cf64, I was not prompt to agree to the deposit agreement. So I didn't and the submission went anyways. But it went with an empty list of Repositories (as seen in the submission details page).

So two things expected that didn't happen here:
- user needs to be prompted to agree to deposit agreement before leaving that page
- If they didn't agree, and the repository list is empty we may want to handle it differently, like as user to exit the workflow. This is related to ticket #426 that @cameronblandford is working on. Let's chat about it tomorrow? 

<img width="1151" alt="screen shot 2018-06-05 at 10 09 53 pm" src="https://user-images.githubusercontent.com/11050142/41011929-379f5f64-690d-11e8-9fd3-c428edf584b7.png">

**Comment by Rytiggy** [comment]
@htpvu you should see this alert if the user does not agree to deposit.

Granted, Ok and cancel should be changed to ok and agree to deposit.

![screen shot 2018-06-06 at 2 18 25 pm](https://user-images.githubusercontent.com/17414914/41057234-96212702-6994-11e8-9616-99b9e0566d80.png)

**Comment by Rytiggy** [comment]
@htpvu the schema for JScholarship needs to be updated, as soon as this is done, it will be fixed. 

```json
 
{
        name: 'JScholarship',
        url: 'https://jscholarship.library.jhu.edu/',
        formSchema: `{
          "id": "JScholarship",
          "schema": {
            "title": "Johns Hopkins - JScholarship brp class='lead text-muted'Deposit requirements for JH's institutional repository JScholarship./p",
            "type": "object",
            "properties": {
              "embargo": {
                "type": "string",
                "default": "NON-EXCLUSIVE LICENSE FOR USE OF MATERIALS This non-exclusive license defines the terms for the deposit of Materials in all formats into the digital repository of materials collected, preserved and made available through the Johns Hopkins Digital Repository, JScholarship. The Contributor hereby grants to Johns Hopkins a royalty free, non-exclusive worldwide license to use, re-use, display, distribute, transmit, publish, re-publish or copy the Materials, either digitally or in print, or in any other medium, now or hereafter known, for the purpose of including the Materials hereby licensed in the collection of materials in the Johns Hopkins Digital Repository for educational use worldwide. In some cases, access to content may be restricted according to provisions established in negotiation with the copyright holder. This license shall not authorize the commercial use of the Materials by Johns Hopkins or any other person or organization, but such Materials shall be restricted to non-profit educational use. Persons may apply for commercial use by contacting the copyright holder. Copyright and any other intellectual property right in or to the Materials shall not be transferred by this agreement and shall remain with the Contributor, or the Copyright holder if different from the Contributor. Other than this limited license, the Contributor or Copyright holder retains all rights, title, copyright and other interest in the images licensed. If the submission contains material for which the Contributor does not hold copyright, the Contributor represents that s/he has obtained the permission of the Copyright owner to grant Johns Hopkins the rights required by this license, and that such third-party owned material is clearly identified and acknowledged within the text or content of the submission. If the submission is based upon work that has been sponsored or supported by an agency or organization other than Johns Hopkins, the Contributor represents that s/he has fulfilled any right of review or other obligations required by such contract or agreement. Johns Hopkins will not make any alteration, other than as allowed by this license, to your submission. This agreement embodies the entire agreement of the parties. No modification of this agreement shall be of any effect unless it is made in writing and signed by all of the parties to the agreement."
              },
              "agreement-to-deposit": {
                "type": "string"
              }
            }
          },
          "options": {
            "fields": {
              "embargo": {
                "type": "textarea",
                "label": "Deposit Agreement",
                "disabled": true,
                "rows": "16"
              },
              "agreement-to-deposit": {
                "type": "checkbox",
                "rightLabel": "I agree to the above statement on today's date",
                "fieldClass": "col-12 text-right p-0"

              }
            }
          }
        }`
      }
```

**Comment by htpvu** [comment]
verified rev. 2ea40c05
