### ISSUE TITLE
minor layout issue - submissions table status column

### ISSUE THREAD

**Issue by jrmartino** [OA-PASS/pass-ember#357]
for "In Progress" submissions, the amber clock icon obscures the final "s" in Progress
(chrome browser in linux (fedora 28) )

**Comment by htpvu** [comment]
Could you attach a screenshots of these kind of things @jrmartino ?

**Comment by jrmartino** [comment]
![screenshot from 2018-05-23 09-46-44](https://user-images.githubusercontent.com/310967/40429330-736621ba-5e70-11e8-8516-dc890b7be9c6.png)

**Comment by cameronblandford** [comment]
This issue is obsoleted by recent commits - we moved to an inline version of the status column that doesn't use floats.
