### ISSUE TITLE
Janky behavior when adding or removing grants during the workflow 

### ISSUE THREAD

**Issue by Rytiggy** [OA-PASS/pass-ember#370]
## Replication
- If a user adds a grant and goes through the workflow to metadata forms and steps through the forms, the right form loads for the first time, then if a user goes back and changes their grant Jscholarship gets removed instead of the grant they clicked.

**Comment by htpvu** [comment]
@Rytiggy the whole grant and metadata form is not working for me on rev. b0b535cb

It seems that the Jscholarship form never did show up. before and after the removal of grant.
