### ISSUE TITLE
Block user from modifying publication metadata if it were pulled from CrossRef

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#374]
When user enter DOI into the submission, we pull in crossref metadata associated with that DOI. Do not let user modify this metadata. Explain so on the form.

If DOI was not entered, then make sure user can manually fill out the forms.

**Comment by htpvu** [comment]
@Rytiggy for some reason, author's names are not readonly 
<img width="608" alt="screen shot 2018-06-01 at 7 49 38 pm" src="https://user-images.githubusercontent.com/11050142/40868017-f57d8c20-65d6-11e8-8f09-df30308a826c.png">

Also the background color of the readonly input fields are a little too intense, can we lighten it a little?

**Comment by htpvu** [comment]
@Rytiggy Article title and Journal name are also things we pull from CrossRef (in the Basic step) - these should not be blocked from being edited too.

**Comment by htpvu** [comment]
@Rytiggy 

i'm terribly sorry, my typo asked for the wrong thing. We want Journal Name AND title to be read-only in BOTH the basic step and the details step

**Comment by Rytiggy** [comment]
@htpvu no problem

**Comment by Rytiggy** [comment]
![screen shot 2018-06-08 at 11 05 59 am](https://user-images.githubusercontent.com/17414914/41165552-f322bdd0-6b0b-11e8-94ff-53d2ba2d1417.png)

**Comment by htpvu** [comment]
looks good.
