### ISSUE TITLE
Branding update: shades of blue

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#380]
Blue used in the policy cards are not part of the brand entity?
There are 4 different shades on this page (for header, policy card, workflow step highlight and button) --> reduce the number of shades used to 2
![screen shot 2018-05-29 at 3 56 36 pm](https://user-images.githubusercontent.com/11050142/40693036-3af1599a-6383-11e8-8ac1-e4c3d00d1683.png)

**Comment by cameronblandford** [comment]
@htpvu the links, workflow nav, and next button are all the same color: #20A8D8. I could try switching more of the color over to the brand colors if you'd like - my only worry is that some institutions might have branding colors that aren't as readable as JHU's dark blue.

**Comment by htpvu** [comment]
rev. 9792cf64 verify
