### ISSUE TITLE
Update Repository step: 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#384]
Change "These are your institutional repositories:" to "Submission to local repositories are optional but encouraged. To opt out of submission into a repository, uncheck its checkbox."
<img width="726" alt="screen shot 2018-05-29 at 9 52 28 pm" src="https://user-images.githubusercontent.com/11050142/40694511-e42c6a70-638a-11e8-8628-d32f50f2b728.png">

**Comment by cameronblandford** [comment]
![image](https://user-images.githubusercontent.com/7365276/40740523-171d4c88-6417-11e8-9b43-b7df4c03b103.png)

**Comment by htpvu** [comment]
verified on rev. b0b535cb
