### ISSUE TITLE
Update JHU Policy card

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#386]
1. Bolden or otherwise emphasize the "Requires submission into JScholarship"
2. IMPORTANT, change "Requires" to "Expects"!!!!

<img width="761" alt="screen shot 2018-05-29 at 10 04 04 pm" src="https://user-images.githubusercontent.com/11050142/40694817-38d540b4-638c-11e8-8f89-7a170c388163.png">

**Comment by cameronblandford** [comment]
![image](https://user-images.githubusercontent.com/7365276/40741233-02785190-6419-11e8-8119-0ddae40ec703.png)

**Comment by cameronblandford** [comment]
What do you think about this?

**Comment by htpvu** [comment]
verified on rev. b0b535cb
