### ISSUE TITLE
Update Grants steps

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#387]
1. update "Review/Provide information about the grant(s)/award(s) that funded this work. This information will help determine which public access policies are applicable to your work. If the work you’re about to submit was not supported by a grant, leave this page blank and go to the next step."
 to read this: 
> Review/Provide information about the grant(s)/award(s) that funded this work. This information will help determine which public access policies are applicable to your work. 
>
> PASS receives information about grants from the University grant management system, COEUS. If you could not find your grant in the below dropdown list, please contact us <Link to contact page>.
>
> If the work you’re about to submit was not supported by a grant, leave this page blank and go to the next step."
<img width="971" alt="screen shot 2018-05-29 at 10 07 21 pm" src="https://user-images.githubusercontent.com/11050142/40694929-d65976e8-638c-11e8-960a-d14988bf1e0c.png">

**Comment by cameronblandford** [comment]
![image](https://user-images.githubusercontent.com/7365276/40741317-4a8e6442-6419-11e8-915d-9bb3b6ac1150.png)

**Comment by htpvu** [comment]
Plaase break this paragraph in three small paragraphs as I described in the initial comment to make the text easier to read. Please link "please contact us" to the contact page.
