### ISSUE TITLE
Remove user's role from his/her display on PASs pages - use just the name

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#389]
<img width="260" alt="screen shot 2018-05-29 at 10 41 06 pm" src="https://user-images.githubusercontent.com/11050142/40695928-6fed5a28-6391-11e8-8262-cb3a49b46467.png">

**Comment by cameronblandford** [comment]
![image](https://user-images.githubusercontent.com/7365276/40741367-64ca0866-6419-11e8-93c0-b1c7ace824d0.png)

**Comment by htpvu** [comment]
verified on rev. b0b535cb
