### ISSUE TITLE
Update Navigation menu

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#391]
1. Hide Grants and Submissions from non-logged-in users
2. Change "Home" to Dashboard
3. Will submitt a separate ticket to pull the latest submissions and grants to the dashboard page.

**Comment by cameronblandford** [comment]
![image](https://user-images.githubusercontent.com/7365276/40741446-9313243c-6419-11e8-82ae-caa8d7be426a.png)

**Comment by htpvu** [comment]
verified on rev. b0b535cb
