### ISSUE TITLE
Update Contact page details

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#392]
Change "For inquiries relating to software development collaborations, please contact:" to "For inquiries relating to acquiring PASS for your institution OR software development collaborations, please contact:
<img width="1171" alt="screen shot 2018-05-29 at 10 54 20 pm" src="https://user-images.githubusercontent.com/11050142/40696298-44edee8a-6393-11e8-8432-9099507947bd.png">

**Comment by cameronblandford** [comment]
![image](https://user-images.githubusercontent.com/7365276/40741538-d0a7852c-6419-11e8-98be-6942ab6db3fc.png)

**Comment by htpvu** [comment]
verified on rev. b0b535cb
