### ISSUE TITLE
Remove "Interested" section from the landing page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#393]
Replace "Making Public Access Policy compliance easier. " in the footer with " Interested in making PASS even better? Want to have PASS for your institution?
Contact us!"

**Comment by cameronblandford** [comment]
![image](https://user-images.githubusercontent.com/7365276/40741740-2e875190-641a-11e8-8e4c-966ce5d6449b.png)

**Comment by htpvu** [comment]
make both Link from Contact AND us. currenlty just contact is linked. looks weird.

**Comment by Rytiggy** [comment]
![screen shot 2018-05-31 at 9 58 16 am](https://user-images.githubusercontent.com/17414914/40786499-2cbc6036-64b9-11e8-8b98-57065b6060e3.png)
