### ISSUE TITLE
change the search buttons on search boxes

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#394]
where it is currently an "x" change it to a magnifiying glass icon 

applies to both the grants page and the submissions page
<img width="544" alt="screen shot 2018-05-29 at 11 06 42 pm" src="https://user-images.githubusercontent.com/11050142/40696726-00518974-6395-11e8-8eb5-fb7c2e0be047.png">

**Comment by cameronblandford** [comment]
@htpvu, the button clears the text in the searchbox, it doesn't initiate a search. The searching happens as you type. Would you like to remove the button?

**Comment by htpvu** [comment]
Yes, let's remove that button. It seems to be confusing.
