### ISSUE TITLE
File icon on the submission review page should not looks like this for a word doc. 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#396]
<img width="335" alt="screen shot 2018-05-30 at 10 02 16 am" src="https://user-images.githubusercontent.com/11050142/40725177-c02f7e26-63f0-11e8-9a58-de7f0648c363.png">

**Comment by htpvu** [comment]
I think we need to rethink how files are represented in the details and review page. the icon looks like, but it's not functional. I can't see the full filename and the format name makes no sense.

**Comment by Rytiggy** [comment]
![screen shot 2018-06-04 at 12 01 55 pm](https://user-images.githubusercontent.com/17414914/40992761-abf6c1d8-68c5-11e8-8d6f-8f4e7b61cef2.png)

**Comment by htpvu** [comment]
verified on rev. 9792cf64
