### ISSUE TITLE
A single file in a submission shows up TWICE in submission details page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#397]
<img width="617" alt="screen shot 2018-05-30 at 10 08 06 am" src="https://user-images.githubusercontent.com/11050142/40725475-8a60c7ae-63f1-11e8-9996-d15a11e127ba.png">

**Comment by htpvu** [comment]
Maybe related to #415

**Comment by cameronblandford** [comment]
As @htpvu, definitely related. Closing in favor of #415 since that one has extra log info
