### ISSUE TITLE
Update the header image on the landing page to rotate amongst these images

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#402]
![son](https://user-images.githubusercontent.com/11050142/40757077-c9d806be-6454-11e8-8f0a-e0552defd9ab.jpg)
![sais](https://user-images.githubusercontent.com/11050142/40757078-c9e67294-6454-11e8-8fe7-b4666b4315b5.jpg)
![apl](https://user-images.githubusercontent.com/11050142/40757079-c9f60966-6454-11e8-8fe0-32fbd5bd2df6.jpg)
![kreiger](https://user-images.githubusercontent.com/11050142/40757080-ca05fc54-6454-11e8-967c-b09df651c1ce.jpg)
![whiting](https://user-images.githubusercontent.com/11050142/40757081-ca1585fc-6454-11e8-9990-06bbd8a72d9b.jpg)
![som](https://user-images.githubusercontent.com/11050142/40757082-ca322cfc-6454-11e8-827b-cc80b673e895.jpg)
![schoolofed](https://user-images.githubusercontent.com/11050142/40757083-ca50fad8-6454-11e8-8f36-32914ce05b71.jpg)
![careybizschool](https://user-images.githubusercontent.com/11050142/40757084-ca70edde-6454-11e8-99ce-4d0c189830d2.jpg)
![jhuhospital](https://user-images.githubusercontent.com/11050142/40757085-ca91aed4-6454-11e8-8d77-18a56eec3173.jpg)
![peabody-header](https://user-images.githubusercontent.com/11050142/40757086-caa22b06-6454-11e8-8a6c-dda4abf3f63b.jpg)
![clarke_131030_1226](https://user-images.githubusercontent.com/11050142/40757100-eb88ce24-6454-11e8-87a7-e647575b54d7.jpg)

**Comment by htpvu** [comment]
@cameronblandford These images aren't rotating on their own, once i click on them, they start rotating. This happened to the logo images too, @Rytiggy fixed it - you may want to check with him. 

Also, can we chat about trying out different crops for some of these pictures?

**Comment by karenhanson** [comment]
The problem is to do with the bootstrap version. The static page uses version v4.0.0, while the ember app uses v.3.3.2 - it seems some of the older versions require that you do an `onload` command to start the rotation.
