### ISSUE TITLE
Remove agency logos from FAQ page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#425]
We dontneed to display logo on this page. Besides, there are two logos in there that dont belong: DHS and NIST. 

Need to more DHS and NIST from the scrolling logos in the landing page as well.

**Comment by cameronblandford** [comment]
@htpvu where would you like the logos to be, if anywhere?

**Comment by htpvu** [comment]
WE only need logos on the landing page. No where else.

**Comment by cameronblandford** [comment]
@htpvu but to be extra clear, we still want a text list of all the agencies on the FAQ page right?
