### ISSUE TITLE
Handle the case where user has no required repo and opt out of the optional ones

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#426]
essentially the submission would go no where - prompt user to exit the workflow where sensible.

**Comment by htpvu** [comment]
Clicking "ok" should take the user back to the "Dashboard" page

**Comment by Rytiggy** [comment]
![screen shot 2018-06-08 at 1 31 49 pm](https://user-images.githubusercontent.com/17414914/41171991-5f534a4c-6b20-11e8-986e-f9cd165a10db.png)
