### ISSUE TITLE
livereload doesn't work in the new shib docker environment

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#433]
Livereload service provided by `ember server` during development cannot be reached by the browser due to the proxy. We do not necessarily want to change the proxy container to pass this port to ember, as it is being used in `pass-docker`.

`https://pass:7020/livereload.js`

For now, we can continue development as before, however, developers must manually refresh the browser to see changes.

**Comment by jabrah** [comment]
Note this is only a thing when using `ember serve` as it is used to automatically reload when there are code changes. Production will have no such feature.

**Comment by htpvu** [comment]
@jabrah is adding comments in repository's  documentation to reflect that fact that we will not address this issue.
