### ISSUE TITLE
Logo sometimes does not load

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#44]
Example: http://localhost:4200/grants/1
Directly entering this URL into the browser, the app will try to load the logo from `localhost:4200/grants/logo.png`. 

Logo image appears as `<img src='logo.png' ... >` in the browser, though in template (application.hbs), it is written as `src='{{rootURL}}logo.png'`. _rootURL_ issue?

**Comment by markpatton** [comment]
But works from http://localhost:4200/grants/. Perhaps some issue with dynamic segments?
