### ISSUE TITLE
Make header alignment on pages consistent

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#440]
There is currently a mixture of left and center aligned headers on the pages. This should be consistent. My preference is to left-align headings. It's easier to read, and on the text-only pages, there are already several different indentations at the top of the white-space, so one less would be tidier.

![titlealignment](https://user-images.githubusercontent.com/4070836/41052534-017815d2-6987-11e8-9201-1c3bca96226b.png)

**Comment by htpvu** [comment]
verified on rev. 10b329f9
