### ISSUE TITLE
widen award number column in the Grant step of submisison workflow

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#443]
THis column could be alittle bit wider i think, even if there will always be a possibility of an award number who needs more space.

**Comment by cameronblandford** [comment]
@htpvu right now the column resizes based on its contents - would you rather it have a larger minimum size?

**Comment by htpvu** [comment]
larger minimum size makes sense

**Comment by karenhanson** [comment]
Closed by PR #546

**Comment by karenhanson** [comment]
verified in 7f2a26bd
