### ISSUE TITLE
When no value is available for Submission dates, NaN is displayed

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#447]
The NIHMS loader sometimes does not populate dates in the submissions if one is not available or it has not yet been submitted. This results in the date being displayed as "NaN/NaN/NaN". It should be blank.
![nihsubmissions](https://user-images.githubusercontent.com/4070836/41064199-d495dd16-69a8-11e8-9897-e9b873a1b33f.png)

**Comment by htpvu** [comment]
verified no rev. 2f8aa8d5
