### ISSUE TITLE
Cannot complete an incomplete pre-loaded NIHMS Submission

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#448]
The image below shows two NIHMS Submissions. One is associated with a RepositoryCopy with a status of "complete". It was not deposited via PASS, but was already in compliance.  The other is NOT in compliance and needs work. There is no way for a user to complete the started submission, or tell which one is not complete - they both appear "not started".  The completed submission should show a link to the RepositoryCopy, while the non-compliant one should should have an option to complete it somehow. Through Your Submissions page, they both look the same and are both "Not Started".

![nihsubmissions](https://user-images.githubusercontent.com/4070836/41064524-cae1ade4-69a9-11e8-8f4c-9e0eab5f6c57.png)

Version tested: 9792cf64

**Comment by htpvu** [comment]
DOne.
