### ISSUE TITLE
Submission Details: "Loading files" message stays when no files found

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#449]
When no files are associated with a Submission (as is the case where completed Submissions are pre-loaded from NIHMS data), the "Loading files..." message on Submission Details page does not go away.

![filesloading](https://user-images.githubusercontent.com/4070836/41065770-b927def8-69ad-11e8-9fb9-f4ca8cc15b79.png)

Using rev. 9792cf64

**Comment by htpvu** [comment]
Not sure how to verify this.

**Comment by htpvu** [comment]
I think there's some subtlety that's not being detected her

- if a submission just got submitted and UI can't pick it up yet, it should say "file is loading"
- if a submisison did not originate from PASS (pulled from other source, it should say "no files"
