### ISSUE TITLE
Create submission for NIH grant does not show NIH repository

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#456]
Using 9792cf64
To replicate:
1) I logged in as a person with an NIH grant. 
2) I clicked Grants, clicked New Submission next to NIH grant
3) Entered a DOI, information was retrieved, Next
4) My grant is listed. Next
5) Correct Policies are shown - NIH and JHU, Next
6) I see only Local Repositories with JScholarship checked. I uncheck it, Next
7) You're done! It says that if I don't plan on submitting to any repositories I can stop at this time.

**Comment by htpvu** [comment]
@cameronblandford I verified this is the issue on rev. 10b329f9 - possible another issue with keying value? big need to fix this asap.

**Comment by cameronblandford** [comment]
@htpvu  will fix this tomorrow morning. should be simple.

**Comment by cameronblandford** [comment]
@htpvu @karenhanson this is an issue with the data we're loading from fedora. Loading a repo requires that a grant is attached to a funder, that funder is attached to a policy, and that that policy is attached to a repository. Currently, none of the funders in fedora have policies attached to them, which is what's breaking that workflow.

**Comment by birkland** [comment]
If I remember correctly, only a small fraction of funders had repositories

**Comment by karenhanson** [comment]
The grant I tested had NIH as the funder and the policy loaded but not the repository. Perhaps you need a newer version of the data to replicate? I was using birkland/assets:2018-06-07
