### ISSUE TITLE
Remove temp workarounds for Journals when assets is updated

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#463]
Related to #279 

A temporary was put in place for the journal picker widget so that it had some functionality. The `assets` container must be updated first, before these workarounds can be removed.

The workarounds in question are mostly tagged with TODO comments and appear in (see https://github.com/OA-PASS/pass-ember/commit/bbc0197aee6425d42abb0bcca71082fd0a944acd):
* `find-journal.*`
* `workflow-basic.js`

**Comment by jabrah** [comment]
Add:
* `workflow-basic.js:90`

**Comment by karenhanson** [comment]
Verified in 7f2a26bd
