### ISSUE TITLE
restyle the respository section in the review page, and possibly the details page. 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#466]
<img width="464" alt="screen shot 2018-06-08 at 8 27 33 pm" src="https://user-images.githubusercontent.com/11050142/41185862-12149a02-6b5b-11e8-8659-c8e580c5ed48.png">

**Comment by htpvu** [comment]
a couple things we should change: 

- the width of the column containing "repositories" should never be so narrow that it needs a second line.
- Put the explanation text in a tooltip: "These are the repositories that PASS will send your submission to"

**Comment by Rytiggy** [comment]
![screen shot 2018-06-09 at 8 46 10 pm](https://user-images.githubusercontent.com/17414914/41197283-4496c45c-6c26-11e8-8132-8cea00124cac.png)

**Comment by cameronblandford** [comment]
LGRTM

**Comment by htpvu** [comment]
verified no rev. 2f8aa8d5
