### ISSUE TITLE
Create a section in Submission Details page for Manuscript IDs

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#471]
section name: "Manuscript IDs"
Its value should be the list of ALL `externalIds` on all associated `repoCopy` objects

**Comment by Rytiggy** [comment]
this is related to https://github.com/OA-PASS/pass-ember/issues/489

**Comment by jabrah** [comment]
Position and all look ok?
![](https://i.imgur.com/BHmke61.png)
