### ISSUE TITLE
Review page has very narrow first text column in Windows/chrome

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#475]
Using: 7f9c04d7
Went through workflow for jscholarship only, uploaded two files. On review page, the first column is very narrow:
![reviewpageformatting](https://user-images.githubusercontent.com/4070836/41196092-f449be88-6c06-11e8-907e-ae6ff5cac118.png)

**Comment by htpvu** [comment]
This needs to be fixed but not critical for user testing

**Comment by karenhanson** [comment]
This has already been fixed as part of another change

**Comment by karenhanson** [comment]
verified in 7f2a26bd
