### ISSUE TITLE
When no DOI entered, Journal and Title not carried through to metadata form

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#476]
Using 7f9c04d7
If I choose not to enter a DOI, but manually type a title and journal name, the title and journal is not carried through to the metadata form for jscholarship. The form is blank and I have to re-enter this information.

**Comment by karenhanson** [comment]
This is a little worse than originally thought. When you get to the metadata form, the Title is grayed out, and empty so you can't edit it and the value from the DOI form is not there.

**Comment by htpvu** [comment]
oh that's not good

**Comment by Rytiggy** [comment]
![screen shot 2018-06-10 at 10 10 53 am](https://user-images.githubusercontent.com/17414914/41202419-0403b186-6c97-11e8-8be7-fee716ea212d.png)
