### ISSUE TITLE
There is no way to view RepositoryCopy for a Submission's publication

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#480]
Once a deposit has been handed off to the repository, the only way to see information about it's progress and see the final result is through the RepositoryCopy information. These RepositoryCopies may or may not be directly related to the Submission (via Deposit.repositoryCopy). Unfortunately there isn't an obvious place to put this information at the moment, but it's important context for the Submission. I would expect a print out of relevant RepositoryCopy information for the Publication on the Submission Details page somewhere. Perhaps the Submission Details page could have a clearer section for Publication-related information that would include the RepositoryCopy information.

**Comment by htpvu** [comment]
a solution for this has been requested in this ticket https://github.com/OA-PASS/pass-ember/issues/471

**Comment by karenhanson** [comment]
Could the manuscript ID column include the status? e.g. [PMID:123456](https://github.com/OA-PASS/pass-ember/issues/480) (in-progress)

**Comment by cameronblandford** [comment]
@htpvu could you close this ticket in favor of #471?
