### ISSUE TITLE
Update Submission table to reflect incomplete submission 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#482]
For submissions with source=other, submitted=false --> status should be "Manuscript expected" with tooltip which says "Funder is aware of this publication and is expecting its manuscript to be submitted"

For submission with source=other, submitted=true --> status should be "Submitted" with tooltip that says "Funder has receive a submission for this publication from a different source. "

<img width="1152" alt="screen shot 2018-06-09 at 4 25 14 pm" src="https://user-images.githubusercontent.com/11050142/41196371-79ddca1c-6c0c-11e8-91b8-9fd93a34ccc6.png">

**Comment by Rytiggy** [comment]
![screen shot 2018-06-09 at 7 43 39 pm](https://user-images.githubusercontent.com/17414914/41197116-dce20fce-6c20-11e8-8ad7-1182c98036ba.png)

**Comment by cameronblandford** [comment]
LGRTM
