### ISSUE TITLE
Tool tip for Submission status on submission table is cut off at the top

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#488]
ALso the text is too small, could the tooltip be wider and allow for larger text?
<img width="501" alt="screen shot 2018-06-09 at 9 48 06 pm" src="https://user-images.githubusercontent.com/11050142/41197505-ed619690-6c2e-11e8-922e-288419bdbd79.png">

**Comment by Rytiggy** [comment]
![screen shot 2018-06-09 at 10 02 14 pm](https://user-images.githubusercontent.com/17414914/41197553-ca7653f8-6c30-11e8-882a-dcf172ab7a61.png)
