### ISSUE TITLE
Update the submission table to display ManuscriptID 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#489]
Manuscript IDs are associated with repoCopy objects.
Relationships amongst the objects are this:
Submission --> publication <-- repoCopy
ManuscriptIDs = repoCopy.externalds
 
<img width="1306" alt="screen shot 2018-06-09 at 9 47 30 pm" src="https://user-images.githubusercontent.com/11050142/41197510-18f3295e-6c2f-11e8-8d71-cd5ecf69dd31.png">

**Comment by Rytiggy** [comment]
this is related to https://github.com/OA-PASS/pass-ember/issues/471
