### ISSUE TITLE
Submissions page does not contain recent submission information

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#492]
If you create a new submission, on the thank you page it links to the `/submissions` list. If you go there from the Thank You page, you need to refresh the page in order to see the Submission you just created. Similarly, if you complete a Submission that was a NIHMS stub Submission, when you visit the `/submissions` list, the status is still "Requires manuscript" with a button to complete the Submission. When you refresh, the status is correct.

**Comment by jabrah** [comment]
I wonder if we can do something as simple as adding a disclaimer to the `thanks` page (seen after clicking Submit) telling the user that the submission (or updates) may take some time to appear in "My Submissions" - and that if it doesn't show up, they should try waiting some amount of time and refreshing.

**Comment by karenhanson** [comment]
Maybe? 2 other thoughts on this, assuming this is to do with the indexer not being updated. (1) could we increase the tempo of the indexer for production? or perhaps there is a way to force an index update when a submission is created? (2) not ideal but at minimum we should remove the link to "Your Submissions" page since that is most confusing when it doesn't show up at all. At least the link to review details has most of the info.

**Comment by jabrah** [comment]
So the rate at which indexing occurs in Elasticsearch can be set with the `refresh_interval` property (https://github.com/OA-PASS/pass-indexer/blob/master/pass-indexer-core/src/main/resources/esindex.json#L4)

ES docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html

**Comment by jabrah** [comment]
Manually setting the `refresh_interval` seems to work with light testing. This could be made permanent by updating the settings in `pass-indexer`. To test manually, you can dynamically update the `refresh_interval` with:

```
curl -X PUT "https://localhost:9200/pass/_settings" -H 'Content-Type: application/json' --insecure -d'
{
  "index" : {
    "refresh_interval" : "1s"
  }
}'
```
