### ISSUE TITLE
Grants table should be sorted by status, with active grants first and terminated grants later

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#497]
if possible, the secondary short criteria would be by project name, alphabetically

**Comment by jabrah** [comment]
Adding an extra sort criteria for `projectName` will require an update to `pass-indexer` : Elasticsearch does not allow sorting on fields indexed as text by default, so this behavior would have to be enabled.

```
"root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Fielddata is disabled on text fields by default. Set fielddata=true on [projectName] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."
      }
    ]
```

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html

Possible solutions:
* Simply not sort on `projectName` or other `text` fields
* Enable this fielddata
* Create a new field explicitly used for sorting?

Looks like any changes to `pass-indexer` that could enable sorting on these fields will require reindexing of the data
