### ISSUE TITLE
Update to NASA Policy object

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#499]
we need to update the relevant part of the Nasa policy object. 
Here it says the policy "Expects deposit into PubMed Central" where it SHOULD say "Requires deposit into..."

Also, you might notice how NIHMS are being rendered with weird characters in the paragraph? Could you please change that as weel
<img width="888" alt="screen shot 2018-06-10 at 11 21 09 am" src="https://user-images.githubusercontent.com/11050142/41203085-87ab2aa6-6ca0-11e8-9460-85a14061b1a5.png">

**Comment by birkland** [comment]
This looks like a minor assets/data update.  The culpret is cutting and
pasting smart quotes, which never works right

**Comment by karenhanson** [comment]
@htpvu I think the part that says "Expects deposit..." might be built into the webpage. It's not part of the policy. I can fix the garbled quotes.

**Comment by htpvu** [comment]
done

**Comment by karenhanson** [comment]
Verified on rev 7f2a26bd
