### ISSUE TITLE
make font size in submission table and other places consistent

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#515]
Note the two different font size in the below screenshot

<img width="432" alt="screen shot 2018-06-10 at 9 39 58 pm" src="https://user-images.githubusercontent.com/11050142/41209078-ee58ff98-6cf6-11e8-8d4b-7cc78b135a1a.png">

**Comment by karenhanson** [comment]
@cameronblandford did you start this, or can i take it?

**Comment by htpvu** [comment]
The text in "Actions" column has changed. I dont think the current text makes sense. Please change it back to "No action needed in PASS" 

Font size looks good though. 
<img width="356" alt="screen shot 2018-06-16 at 9 34 19 pm" src="https://user-images.githubusercontent.com/11050142/41503901-18132b6e-71ad-11e8-9661-dc6b7368e9d5.png">
