### ISSUE TITLE
make font size more readable across the site

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#516]
Test out with Sayeed

**Comment by cameronblandford** [comment]
Is there an example of text that isn't readable enough?

**Comment by htpvu** [comment]
@cameronblandford the whole site is said to be hard to read

**Comment by htpvu** [comment]
@jabrah maybe we can consult the library's website for this https://www.library.jhu.edu/

**Comment by jabrah** [comment]
Only difference I see between other JHU sites and PASS is the font. Other JHU sites use the same font-size as PASS, but where JHU sites tend to use the font `gentona`, PASS currently has `gentona-light`

**Comment by jabrah** [comment]
Edit to last comment: the 2nd picture isn't actually `gentona` font :) 
It was a fallback font, set by the browser

**Comment by karenhanson** [comment]
Tested in 566f3441, this does not look good on Windows. I think there is one or more font that does not render well on Windows. Perhaps the stylesheet can be configured to either use fonts that are both known to work well on different OS and are easy to read. 
![image](https://user-images.githubusercontent.com/4070836/41477591-c0f250e6-7092-11e8-84a1-4d4a29feaba5.png)
![image](https://user-images.githubusercontent.com/4070836/41477756-4c8ea2b2-7093-11e8-88ee-52e416b61c63.png)

**Comment by htpvu** [comment]
verified rev. 96d1830b
