### ISSUE TITLE
2.Grants step: "Add Grants" select box does not react to already listed awardNumbers

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#522]
I log in as a person with one grant. Go to Grants page. Pick `Create Submission` for that Grant. On step `2. Grants`. Award number is already added, but `Add Grants` shows that one Award Number. I select it, nothing happens. I remove the one Award Number from the list, `Add Grants` still has that Grant selected. I cannot re-add that Award Number without leaving the page and coming back to it so that the `Add Grants` box clears and i can re-select the Award Number.

One suggestion for fixing this is to make it so that selecting something in the `Add Grants` list blanks out the box afterwards so values do not get stuck in there. It might also be useful to have a "Grant already added" message so that the user doesn't think it isn't working. Another option is to not display grants that are already added.

**Comment by htpvu** [comment]
Need to replicate disbehavior for clarification

**Comment by htpvu** [comment]
@karenhanson could you tell me which test user has 1 grant so i could test this?
