### ISSUE TITLE
In submission workflow, policy sometimes does not appear

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#523]
Going through the Submission workflow, after selecting grants, sometimes only the JHU policy card appears, when other policy cards should be present.

Seems to occur when adding a Grant during the `workflow-grant` step from the dropdown.

## Test
* Login to `nih-user`
* Navigate to new submission workflow (not from a grant)
* Enter basic info to get to the Grant step
* In the dropdown, select `R01EY012124 Regulation of Synaptic Plasticity in Visual Cortex`
* Click Next to show Policies step
  * Policy may or may not appear

**Comment by htpvu** [comment]
verified
