### ISSUE TITLE
5. Details: Embargo date has no constraints

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#529]
The embargo date shows a placeholder "mm/dd/yyyy". I can then write _any_ value (e.g. a space) in there and hit next. If this is not by design, consider date validation for this field. It seems important that this value is correct since it deals with copyright constraints etc.

**Comment by karenhanson** [comment]
Just noticed you can actually enter a month, day, and leave the year as "yyyy" and it will accept it.

**Comment by htpvu** [comment]
Will updated ticket here: https://github.com/OA-PASS/pass-ember/issues/583
