### ISSUE TITLE
For submission that did not originate from PASS, hide the incomplete Submitted date text

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#536]
<img width="1292" alt="screen shot 2018-06-11 at 11 30 45 pm" src="https://user-images.githubusercontent.com/11050142/41268749-b3f92fba-6dcf-11e8-9683-a0cbf98dc761.png">

**Comment by jabrah** [comment]
Is there an example of this in our current test data?

**Comment by karenhanson** [comment]
verified in 566f3441
