### ISSUE TITLE
Update to the repositories step in submission workflow

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#537]
1. Change "Local Repositories" in the repositories step to "Institutional Repositories"
2. After repository name , attach the name of the agency whose policy will be satisfy by deposit into this repository: eg: 
- PubMed Central - required by National Institutes of Health
- PubMed Central - required by Center for Disease Control and Prevention
- JScholarship - required by Johns Hopkins University
3. If Jscholarship is the only target repository, hide the checkbox, and dont give user a way to opt out of it. 

Consideration: the desired effect is to convey that Jscholarship deposit is optional if user is submitting to PMC. But we need to balance between a tailored message and keeping the logic of loading policies & repository extensible and dynamic. 

We should chat and brain storm some about (3)

**Comment by karenhanson** [comment]
@jabrah tested this, 1 & 2 work, but the checkbox needs to be hidden for (3) unless there has been an offline discussion to leave it visible but grayed out.

**Comment by htpvu** [comment]
Greying out is ok, if it is too much work for the time being. But we prefer hidden text bow.

**Comment by karenhanson** [comment]
verified in 566f344
