### ISSUE TITLE
Consolidate information about repository, deposit and repoCopy in a view that make sense to user

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#539]
In submission details page

Details to come

**Comment by jabrah** [comment]
Original Submission Details page:
![screenshot from 2018-06-14 10-33-37](https://user-images.githubusercontent.com/5167587/41418796-80b0f19c-6fbe-11e8-9200-3a24f0386f4b.png)

**Comment by jabrah** [comment]
First draft at consolidating repositories, repositoryCopies, deposits:
![screenshot from 2018-06-14 10-33-15](https://user-images.githubusercontent.com/5167587/41418930-d686ab5c-6fbe-11e8-932d-c718254bb29c.png)

**Comment by jabrah** [comment]
Each `repositoryCopy` object related to the submission should be displayed and organized by repository. The status for each should be inferred from the `repositoryCopy.copyStatus` like:
*  `accepted|in-progress` display as "in progress"
* `stalled` as "stalled"?
* `complete` as "complete"

**Comment by htpvu** [comment]
We need to account for deposit that do not have or have not had RepoCopy objects. So the information needs to start out with the list of repositories attached to the submission object:
For each repository:

- display repository name
- display status:
-- RepoCopy exists with status `complete`: `complete` (tooltip: Submission to this repository was accepted and processed that the repository. ID(s) have been assigned to the submitted manuscript)
-- RepoCopy exists with status `stalled`: `stalled` (tooltip: We detected that the target repository has stalled processing of your manuscript. Please sign on to the target repository's system for more details)
-- RepoCopy does not exist: `submitted` (tooltip: PASS has received your submission. Your submission has been sent to the target repositories or is in queue to be sent)
- display repoCopy's external Ids if they exist.

**Comment by jabrah** [comment]
Add status check:
* `repoCopy exists && submission.source == 'other' && submission.submitted == false` then display status `Manuscript expected` with appropriate tooltip

**Comment by htpvu** [comment]
THis looks rather beautiful!
