### ISSUE TITLE
2. Grants: Difficult to find a specific grant in grant picker

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#550]
If you have a large number of grants, it is difficult to find a specific grant in the dropdown list. Need to be able to search or sort the `Add Grant` list. 

Note: This ticket may need refinement. It seems there was an autocomplete option at some point but it was removed - there may be some history here to dig into. See #292, #322, #424

**Comment by htpvu** [comment]
@cameronblandford how was this implemented? I know we have removed the auto complete grant option.

**Comment by htpvu** [comment]
The easiest way to make this easier is to sort grant list by grant's name?

**Comment by htpvu** [comment]
grants are now sorted by end date
