### ISSUE TITLE
Add FAQ explaining when publishers will auto-submit to NIH

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#551]
Need FAQ to explain the different paths for publishers with regards to NIH submissions and the circumstances under which you will need to do a submission through PASS. This should link to the relevant NIH pages and the list of publishers/journals that will do the submission for you.

Text will be added when available

**Comment by htpvu** [comment]
@karenhanson the propose FAQ looks great!

I would only cross out this " ... and without having to interact with the NIHMS system" - because people are still required to log on to NIHMS to approve various things.
