### ISSUE TITLE
4. Repositories: Need to reword text under "Institutional Repositories" heading and add FAQ

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#552]
Wording under "Institutional Repositories" heading is not clear enough for explaining why you should include JScholarship. Note that the wording should still be appropriate when JScholarship is the only option and the user cannot opt out. There should be a FAQ for this to link to and provide more info.

Text will be added when available

**Comment by karenhanson** [comment]
Proposed text under Institutional Repositories heading in step 4:

A Submission to the following will put you in compliance with your [institution's open access policy](/faq#institution-policy). If you are already making your publication openly available elsewhere (e.g. PubMed Central), this may be optional.

**Comment by karenhanson** [comment]
Propose FAQ text. 
What is my institution's open access policy?
As of July 1, 2018, Johns Hopkins University has implemented an open access policy that requires all peer reviewed articles be made openly available. To learn more about this policy visit the [Office of the Provost's webpages on Open Access at Johns Hopkins](https://provost.jhu.edu/about/open-access/)

**Comment by htpvu** [comment]
Proposed FAQ text.
What is my institution's open access policy?
As of July 1, 2018, Johns Hopkins University will put in effect the university wide open access policy that requires all peer reviewed articles be made openly available. To learn more about this policy visit the Office of the Provost's webpages on Open Access at Johns Hopkins

**Comment by karenhanson** [comment]
Proposed FAQ text.
What is my institution's open access policy?
As of July 1, 2018, Johns Hopkins University will put in effect the university wide open access policy that requires all scholarly articles produced by full-time faculty members be made openly available. To learn more about this policy visit the Office of the Provost's webpages on Open Access at Johns Hopkins

**Comment by htpvu** [comment]
sounds good to me

**Comment by htpvu** [comment]
perfect!
