### ISSUE TITLE
7.Review: Remove "hover over text for full text" notice and wrap file description

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#554]
On the final review page, in the files section, a note says "Hover over text for full text" even when you do not have a description, making it unclear what this refers to.  Unless there is a reason to truncate the description, perhaps the full description could be displayed and the "hover over..." help text removed.

**Comment by JeffSpies** [comment]
User story: "User is not sure what to hover over."

**Comment by Rytiggy** [comment]
## Before fix
![screen shot 2018-06-20 at 10 09 48 am](https://user-images.githubusercontent.com/17414914/41670952-c0d6dad8-7483-11e8-8ed5-24f13ddaaa4d.png)

## After fix 
![screen shot 2018-06-20 at 12 15 08 pm](https://user-images.githubusercontent.com/17414914/41670983-d0e88f34-7483-11e8-8db6-0d6e3a94d21d.png)

**Comment by Rytiggy** [comment]
https://github.com/OA-PASS/pass-ember/pull/612
