### ISSUE TITLE
1.Basics: Add contact link for when a journal title is not found 

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#555]
Currently we have ~27,000 journals loaded representing every journal ever cited in PubMed. This is not necessarily a complete list. We need to handle when a user does not have a DOI and their journal title is not in the list. 

The ultimate solution for this may need to be more involved, but as a basic patch, add a link to the contact page next to the Journal list saying, "Can't find your journal? Contact us to add it". We can then manually load missing journals..

**Comment by Rytiggy** [comment]
## Before 
![screen shot 2018-06-21 at 10 18 58 am](https://user-images.githubusercontent.com/17414914/41724894-98c1f136-753c-11e8-813d-5e522a780b3c.png)
## After
![screen shot 2018-06-21 at 10 18 42 am](https://user-images.githubusercontent.com/17414914/41724906-9e46ecba-753c-11e8-9d53-ebdf962f266d.png)
