### ISSUE TITLE
4. Repositories: Reword text to clarify that PASS will do the submission for researcher

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#556]
Current text "Based on the information about the funders and journal you have provided, you are required to deposit your manuscript/article into" does not indicate PASS will help you with this. Should be changed to:

"Based on the grant and journal information provided, you are required to submit your manuscript to the repositories below. PASS will help you to create submissions for these in the following steps:"

**Comment by htpvu** [comment]
great!
