### ISSUE TITLE
5. Details: When not using a DOI, no fields are available to complete

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#557]
If I do not enter a DOI, on the `1. Basics` step, when I reach the `5. Details` step, only the Journal and Title field are displayed and though it says "provide additional information" I can't because there are no fields to fill in.  When DOI is not populated, the user should be able to fill in other fields.

**Comment by htpvu** [comment]
When not using DOI, besides Journal and title, we should only ask for embargo information. 

Other fields aren't required for submission. and no one we tested with wanted to fill them in. They all just seemed confused about those extra fields.
