### ISSUE TITLE
6. Files: Add placeholder text to clarify what is expected in file description

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#559]
Feedback during testing was that it is unclear what the description is for. Add placeholder text that says:  "brief descriptive label, may be displayed in some repositories"

**Comment by jabrah** [comment]
Implemented currently as a Tooltip on the column header

**Comment by karenhanson** [comment]
I left this for @htpvu to review, wanted to make sure tooltip instead of placeholder OK.
