### ISSUE TITLE
5. Details: Make embargo fields visible regardless of other conditions

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#560]
Currently the embargo fields are not visible on the `5. Details` page whether you pick a DOI or use Journal/Title. The embargo fields should be visible on the Details page regardless of other conditions.

I believe this may be related to #557

**Comment by htpvu** [comment]
Currently, on rev. 96d1830b, embargo date input field is shown already. so i'll close this. There are some usability issue with this field, that will be recorded in a different ticket. https://github.com/OA-PASS/pass-ember/issues/583
