### ISSUE TITLE
Add FAQ on how to negotiate copyright when publishing and who to contact for help

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#561]
Text for this will be added when available

**Comment by htpvu** [comment]
@karenhanson this one should point to the office of scholarly communication - but that office is such a mess i have to figure out what the heck to do with this.

**Comment by htpvu** [comment]
Let's add a FAQ entry on our site about this. Point people to Robin Sinn at the Office of Scholarly Communication (rsinn@jhu.edu)

**Comment by karenhanson** [comment]
@htpvu I think I need a bit more context on what to include here - what is the question and what kind of information should the answer include other than contact info?

**Comment by htpvu** [comment]
Question: "How do I negotiate copyright agreement for my publication so I can comply to Public/Open Access Policies?"
Answer: Publication copyright agreement can be negotiated. If you need help with this, please contact Robin Sinn at the Office of Scholarly Communication.

**Comment by karenhanson** [comment]
@htpvu I expanded this a little, what do you think?

**How do I negotiate a copyright agreement for my publication to comply with Public/Open Access Policies?**

Many journals make allowances for self-archiving and compliance with access policies implemented by a funder or institution. You can look up a publisher's policy for copyright and self-archiving on the [SHERPA/RoMEO website](http://www.sherpa.ac.uk/romeo/index.php). If a journal does not allow open sharing of your article, you may be able to negotiate with them to make an exception. For help with copyright negotiation, or any other copyright related questions, please [contact Robin Sinn at the Office of Scholarly Communication](https://pass/app/contact).
