### ISSUE TITLE
Display information about the manuscript throughout the submission workflow

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#564]
Under or near to the "New Submission" heading, display some simple formatted article metadata that will be visible through each workflow step. Maybe something like...

### New Submission 
_for_ ***Some Title of Some Article Here (Publication date, if known)***

**Comment by Rytiggy** [comment]
## Verification: below is the change that should happen in this ticket. 
### Before 
![screen shot 2018-06-18 at 2 01 58 pm](https://user-images.githubusercontent.com/17414914/41553661-698e37d2-7300-11e8-9e61-d96fd14205c6.png)
### After 
![screen shot 2018-06-18 at 2 02 20 pm](https://user-images.githubusercontent.com/17414914/41553685-76cad4aa-7300-11e8-8ecd-88b7009cac60.png)

**Comment by htpvu** [comment]
@Rytiggy I dont think that will work. Submission title could get verylong. I would leave the `New Submission` header as it was and add the article title as a `sub title`. Try to make it more obvious so user dont miss it.

**Comment by htpvu** [comment]
Assigned to @jabrah so he can italicize the subtitle text.
