### ISSUE TITLE
 Your Submissions: Add text to clarify what this list contains

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#566]
Add text to top of `Your Submissions`:
"This list contains all Submissions that you have initiated through PASS. If you have an NIH grant, it may also contain pre-loaded information about incomplete, in-progress, or completed Submissions to PubMed Central. Find out more about these pre-loaded NIH submissions on the FAQ page" (link to FAQ)
On FAQ page:
### What information about NIH submissions is pre-loaded into PASS?
Records of NIH submissions in PASS go back to January 2013. Each night, updated Submission information is loaded into PASS from the NIH Manuscript Submission system (NIHMS). This information contains the public access compliance status of articles associated with NIH grants. If you are a PI on an NIH grant and have articles that are associated with those grants in PubMed, you may see the following on Your Submissions page:
(1) Information about completed or in-progress Submissions, some of which may have been initiated outside of PASS. No action is required for these Submissions.
(2) Information about manuscripts that have not yet been received by NIH for deposit into PubMed Central. These will appear in PASS as "requiring a manuscript" and can be completed through PASS to put the manuscript into compliance. 
The information for these submissions comes directly from NIH, please feel free to contact us if there are problems with your data so that we can pass the information on to NIH.

**Comment by htpvu** [comment]
Let me run this by Sayeed

**Comment by htpvu** [comment]
text for Submisisons page:

- also change page title to Submissions (Remove "your")

> This list contains all Submissions that you have initiated through PASS. If you have an NIH grant, it may also contain pre-loaded information about incomplete, in-progress, or completed Submissions to PubMed Central that cite a grant for which you are the PI. Find out more about these pre-loaded NIH submissions on the FAQ page"

**Comment by htpvu** [comment]
Text for FAQ:
What information about NIH submissions is pre-loaded into PASS?

> Records of prior NIH submissions displayed in PASS go back to January 2013. Each night, updated Submission information is loaded into PASS from the NIH Manuscript Submission system (NIHMS). This information contains the public access compliance status of articles associated with NIH grants. If you are a PI on an NIH grant and have articles that are associated with those grants in PubMed, you may see the following on Your Submissions page:
> (1) Information about completed or in-progress Submissions, some of which may have been initiated outside of PASS. No action is required for these Submissions.
> (2) Information about manuscripts that have not yet been received by NIH for deposit into PubMed Central. These will appear in PASS as "requiring a manuscript" and can be completed through PASS to deposit the manuscript into compliance.
> The information for these submissions comes directly from NIH. Please feel free to contact us if there are problems with the information so that we can contact NIH.
> 
>

**Comment by htpvu** [comment]
verified on rev. 96d1830b
