### ISSUE TITLE
Update Grants table to pull in grants for which logged-in user is either PI or Co-PI

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#572]
Update the Label in Grant details page from "Co-PI(s)" to ""Co-PI(s)/PI(s)"

**Comment by jabrah** [comment]
Should this change also be applied to the Grants picker in the submission workflow?

**Comment by htpvu** [comment]
@jabrah yes! thanks for pointing that out.

**Comment by htpvu** [comment]
Based on our discussion with Aaron and Jim, please restrict the grants pulled back to those with end date of 1/1/2011 and later.
