### ISSUE TITLE
Add text to the thank you page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#573]
If a submission has PMC as a target repo, display text to inform user about what to expect next from NIHMS.  Wording to come

**Comment by karenhanson** [comment]
There is a more general issue at #562 - perhaps these can be merged into one

**Comment by htpvu** [comment]
Add a section in thank you page titled "What to expect"

Under it, the following text:

> Submisision to PubMed Central (PMC), via National Institutes of Health Manuscript Submission (NIHMS), requires 2 additional steps. You will be contacted within a few days to approve the processing your manuscripts on NIHMS. Once approved, your manuscript will be formatted for display on PMC. A final approval will be required before your manuscript is ready for publication on PMC. For more information about the submission workflow in NIHMS, pleas see here: https://www.ncbi.nlm.nih.gov/books/NBK3846/

> Submission to JScholarship will done on your behalf. You can expect the submitted manuscript to be assigned an identifier and access url within (need to check with Elliot)

**Comment by karenhanson** [comment]
@htpvu talked to Elliot, it's difficult to put timing on JScholarship, there are a few different factors - whether someone needs to do manual processing on DSpace end, whether deposit needs to do a retry etc.

**Comment by karenhanson** [comment]
How about: 
Submission to JScholarship will done on your behalf. Once the submitted manuscript is processed by the repository, an access URL will be available through PASS. Processing times may vary.

**Comment by htpvu** [comment]
let me ask the Jscholarship folks about this to be sure
