### ISSUE TITLE
5.Details Text at top of Publication Detail step looks different from other steps

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#576]
There is an additional style set here called "lead" that makes this text look different from text at the top of other pages. All workflow steps should be styled with same font under heading.  (Note there is a pending ticket to deal with the badly rendered font for Windows, the issue is the grey text under "Publication Details".

![image](https://user-images.githubusercontent.com/4070836/41478631-7b90607a-7096-11e8-8eb8-962e84296531.png)

**Comment by htpvu** [comment]
verified on rev. 3183c0c4
