### ISSUE TITLE
Embargo date field is hard to use

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#583]
Add to the help text of "Embargo End Date" field in _**italic bold**:_ **_"If this publication is not under embargo, please this field blank"_** 
Calendar doesn't pop up unless click on the arrow in the FAR right of the field. The scroll bar for increasing the month/day/year is downright mysterious. Does not support typing in (which I *think* is the intention?)

Can we make the calendar popup when user click on the input box. and get rid of the scrolling bar? <img width="1265" alt="screen shot 2018-06-16 at 10 09 10 pm" src="https://user-images.githubusercontent.com/11050142/41504070-08961bc4-71b2-11e8-933c-53392c49f5f0.png">

**Comment by Rytiggy** [comment]
Talked with Hanh about this ticket, updated requirements: make input field smaller due to not being able to make date picker open on click. remove the scroll bar for increasing the month/day/year. add the updated helper text
