### ISSUE TITLE
[WIP]Repositories are not being attached to Submission object at creation!!!!!!

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#584]
on rev. 96d1830b

I verified (through the view of ember inspector data) that the submission object had an empty respositories list. This submission should have had JScholarship in it. 

I looked at the resources in the repo, this submission object had NO repositories attached to it

 <img width="1317" alt="screen shot 2018-06-16 at 10 20 53 pm" src="https://user-images.githubusercontent.com/11050142/41504137-f0668640-71b3-11e8-87fa-fbe941a0f76c.png">

**Comment by htpvu** [comment]
need more investigation

**Comment by Rytiggy** [comment]
@htpvu I have not been able to replicate this. Could you provide more specific steps to reproduce the bug?

**Comment by karenhanson** [comment]
@Rytiggy @htpvu I know of 3 scenarios where you can get an empty repository list. 

Log in as `ed-user`, pick a Department of Education grant, then either (1) de-select JScholarship and only submit to a linked repository (e.g. ERIC), or (2) don't check the agreement so it removes JScholarship, then the repository list is empty. The 3rd scenario is if you only have JScholarship and do not check the agreement but proceed anyway, it will take you all the way to the end of the workflow and you will get a submission with no repositories. I have not seen a case where you submit to JScholarship correctly and the repository list is empty - is it possible that you did not check the agreement and it completed anyway?

**Comment by htpvu** [comment]
@Rytiggy @karenhanson - i think what you describe karen are real scenarios created by the gap in code logic. what i observed were in the implemented code paths, but something were misbehaving. I haven't been able to reproduce the original bug either.

In regard to the 3 scenarios that youdescribed, at least one should have been address by previous work by @cameronblandford - i'm not sure what happen to the popup asking user to leave the workflow. so we shold look into these thigns.
