### ISSUE TITLE
The file upload step of the workflow should wait until the file is uploaded before proceeding to the thank you page

### ISSUE THREAD

**Issue by JeffSpies** [OA-PASS/pass-ember#588]
We need the following analysis:

- Is the upload page not blocking while uploads are in progress?
- Do we need to use an upload library?
- Can we display a spinner/progress-message during file upload?

That could generate one of two tickets:

1. Replace current file upload with X upload library
2. Use completion event to progress in workflow after files are uploaded; add spinner/progress-message.

**Comment by JeffSpies** [comment]
@htpvu do you want to object creation to hire PRIOR to upload of files? Is that the requirement or is the requirement to fix the problem assuming the true flag will be set only when files are uploaded?

**Comment by htpvu** [comment]
@JeffSpies it is a requirement not to have a submission object with `submitted=true` until after the files are uploaded. 

i didn't see that message until just now

**Comment by htpvu** [comment]
moving back to todo to see if we can resolve the problem of submission object having submitted status BEFORE file upload is done.
