### ISSUE TITLE
[WIP] if the user click "OK" on the current deposit agreement popup, UI takes user to the next screen and user loses the deposit agreement form.

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#591]
Expected behavior: dont remove the repository until the review step. 
<img width="646" alt="screen shot 2018-06-17 at 12 11 51 am" src="https://user-images.githubusercontent.com/11050142/41554526-21ee0a26-7303-11e8-8440-fd74f5efabde.png">

**Comment by karenhanson** [comment]
The original issue is fixed, my comment is referring to something different. I will test this and log a new issue if it is still a problem.

**Comment by karenhanson** [comment]
Actually, there is already an issue: https://github.com/OA-PASS/pass-ember/issues/693
