### ISSUE TITLE
Asset image update relating to ED policy and integrationType on repositories objects

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#605]
There is an extra "m" in "employees". This requires an assets image update to fix. 
"Department of Education requires awardees - grantees or contractors - who are receiving ED funding to carry out research, as well as ED **emmployees** who produce peer-reviewed scholarly publications, to submit their final peer-reviewed manuscripts to ERIC (Education Resource Information Center) when accepted for publication. Programmatic integration between PASS and ERIC is not available at this time, but a link to ERIC submission portal, along with publication metadata we have collected so far can be found at the end of the submission steps to help you start an article/manuscript submission in ERIC. "

**Comment by htpvu** [comment]
Additionally, update the `integrationType` field on `Repository` objects:
ERIC (for ED)  and DEC (for USAID) are `web-link` repos
JScholarship (for JHU) is `full` repo
PMC is `one-way` repo

**Comment by birkland** [comment]
I'm adding acls to the data now, and will do a dump for Derek.  So I can probably do this tomorrow.  In the meantime, I'm letting things run overnight.  Please don't touch `assets` until that's done :)

**Comment by htpvu** [comment]
@birkland dont worry we're not touching assets until after the launch. hence the `DEFFERRED` tag

**Comment by jabrah** [comment]
USAID policy and associated repository need to be updated as well.
* `repository.name` & `repository.formSchema`: Development Experience Clearing**~~s~~**house (DEC) 
> extra `s` in the Clearing(s)house should not be there
* `policy.url` should be `https://www.usaid.gov/open/public-access-plan`

**Comment by birkland** [comment]
OK.  Got these all in.  Eventually a new assets container will be floating your way.

**Comment by htpvu** [comment]
Done
