### ISSUE TITLE
New faq entry please

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#611]
**What to expect after submitting through PASS?**

For submissions to PubMed Central:
- Within a few hours after submitting your manuscripts and associated files through PASS, you will be contacted by the National Institutes of Health Manuscript System (NIHMS) to approve the processing of the submission in NIHMS. At this point you will be given NIHMSID, which could be used to demonstrate Public Access Policy compliance while your manuscript is being processed. 
- NIHMS staff will then review the submission for completeness. Complete submissions are converted to archival XML, making them ready for PMC publication. PMC-ready documents are checked for accuracy. 
- Once the formatting process completes, you will be contacted again for the Final-Approval of the PMC-ready documents or request changes if necessary.
- PMCID will be assigned once the Final-Approval is received and the manuscript is matched to a PubMed record with complete citation information.
- Manuscript is made available in PMC following the publisher-required embargo period (if applicable).
(More on the NIHMS process here: https://www.ncbi.nlm.nih.gov/books/NBK3846/)

For submissions associated with NIH funding, PASS will be able to retrieve and display NIHMSID and PMCID as they become available. 

For submissions related to the Department of Education's ERIC repository and US Agency for International Development's DEC repository, PASS does not track the submissions to these repository, but will keep a record of your interactions on PASS relating to these submission. 

We are continuing to work with different funding agencies to create better and more meaningful integration between our system and their in order to bring our users more useful features and workflows.

**Comment by karenhanson** [comment]
@htpvu based on the recent changes, is it still accurate to say it tracks submissions to these repositories? we removed the repo link on the submission.  Also, what should I say about the JScholarship repo - just that it will be processed and assigned an ID within several hours?
