### ISSUE TITLE
Submission table: Long manuscript IDs do not wrap, they cross into next column

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#631]
Truncate or wrap long manuscript IDs

![image](https://user-images.githubusercontent.com/4070836/41742719-da3b24cc-756c-11e8-8678-37b9b8737c41.png)

**Comment by karenhanson** [comment]
@jabrah  Example of an ID from JScholarship:
Dev: http://pass:8181/xmlui/handle/1774.2/123456
Live: http://jhir.library.jhu.edu/handle/1774.2/123456
Need to double-confirm with @htpvu but this should be displayed as Manuscript ID "1774.2/37577" with the full ID available on hover-over. AccessUrl will be added.

**Comment by htpvu** [comment]
I can confirm!

**Comment by htpvu** [comment]
@karenhanson @jabrah when you guys got that implemented, please send a screenshot of the result so i can show sayeed before finishing it up. to make sure it's cool with him
