### ISSUE TITLE
Files with size > ~100mb don't upload properly

### ISSUE THREAD

**Issue by cameronblandford** [OA-PASS/pass-ember#635]
Instead of the files being uploaded, the tab crashes when attempting to load the entire large file into local memory. This could also be a symptom of having to write the entire file binary to the body of a POST request. Regardless, loading the whole file at once ceases to be an option after a certain size is reached, and due to fedora not (currently?) supporting multi-part file uploads, there's not a lot that can be done on the front-end side.

**Comment by birkland** [comment]
Do browsers have to load it in memory?  Streaming (transfer encoding
chunked) would work.  It looked like there were some newer
streaming-friendly APIs in one of the various js specs (reading/writing as
a stream rather than byte array)

**Comment by htpvu** [comment]
what is the actually cut off in size? it's an extreme edge case for a manuscript file or supplement file to be larger than 100mb. 

at this point we will need to just put a file size limit notification on the file upload page.

**Comment by birkland** [comment]
It looks like the code reads the contents of the file into a byte array, so
it is browser and memory dependent.  Fedora has no limit.  Maybe we just
say 100, then fix the upload implementation later.

**Comment by cameronblandford** [comment]
@htpvu it's somewhere between 115MB and 140MB. I think 100MB is a good clean limit that's not cutting it too close. File size validation and some text explaining the file size limit wouldn't be much work.

**Comment by cameronblandford** [comment]
@birkland didn't mean to imply that fedora had a hard limit, i wrongly assumed there'd be some sort of soft or hard limit to the size of a post request (just did some quick research and i was wrong, it's a configurable setting on the server-side)

**Comment by cameronblandford** [comment]
I imagine it's a browser memory (or maybe more specifically tab memory on chrome?) issue for sure.

**Comment by htpvu** [comment]
@cameronblandford could you please implement that for us (size validation and proper messaging)?
