### ISSUE TITLE
look up additional metadata about journal for a submission during submission workflow

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#637]
We need to get these things from NIH's eUtils api:
1. ISSN's pub-type 
2. Journal's NLMTA value

* Given an ISSN, this information can be acquired by first hitting the below search end point and capture the `<id>` field value
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=nlmcatalog&term=0006-2952[issn]
* Given the above `<id>` value, use this end point to look up associated ISSNs, their pub-type and NLMTA value for that journal 
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?db=nlmcatalog&retmode=json&rettype=abstract&id=101032 
(note that we're only interested in print and electronic issn pubtype and NLMTA is captured as `"medlineta"` in the request's response. )

the above information need to be presented in the metadata blob of the submission for the deposit service to consume. the fields name should be `nlmta`, `ISSN` and `pub-type`. some data structure might be needed to capture the combo of ISSN and its associated pub-type in the case of multiple ISSNs. Please sketch out the intended locations/names of the fields in the blob ahead of time to give deposit service folks time to implement the parsing. 

Bonus point for being able to display these fields during the workflow, but it's not critical

**Comment by jabrah** [comment]
First link will be interesting: `&term=<your-issn-here>[issn]` number needs to be labeled as ISSN in square brackets
