### ISSUE TITLE
On the review page of a submission, the file link is example.com

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#639]
Not sure if this is an artifact of being in test mode, but on the review page of the submission workflow, files have anchor tags populated with the URL "example.com".

**Comment by htpvu** [comment]
That needs to be moved. They’ve been over looked.

Hanh Vu
Project Manager, Data Conservancy
Sheridan Library, Johns Hopkins University



On Fri, Jun 22, 2018 at 1:16 AM -0400, "Karen Hanson" <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if this is an artifact of being in test mode, but on the review page of the submission workflow, files have anchor tags populated with the URL "example.com".
