### ISSUE TITLE
Clicking submit button does not indicate that your click worked

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#647]
Sometimes there is a longish pause between hitting submit and reaching the "Thank You" page. I often hit the Submit button several times thinking it didn't work. It would be helpful if there was a visual cue such as a spinning or processing icon to show that you clicked the button and PASS is working on the submission.

**Comment by htpvu** [comment]
This behavior is becuase the UI blocks after user clicks submit to upload files. User is not redirected to the next page until file upload is done. some user feedback as suggested by Karen would makes sense.
