### ISSUE TITLE
Metadata form: Author field display issues

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#660]
There are several issues with display of author fields on the metadata form. The first 2 are vital to fix, the others are bonus fixes.

* button to add a second author disappears quickly when you leave the field and is almost unusable 
* the "value is not unique" message seems to appear whatever you enter  
* (minor) there is no gap between author field and embargo, and 
* (minor) maybe "Add author" on the button, not "Add new item"
* (minor) don't italicize the "+" on the "Add new item" button (edited)

![image](https://user-images.githubusercontent.com/4070836/41871279-73a72e86-788c-11e8-9059-30d27d79cf28.png)

![image](https://user-images.githubusercontent.com/4070836/41871271-6c369902-788c-11e8-8c19-32d341f4cc5a.png)

**Comment by jabrah** [comment]
Temporary work around in place: Do not allow users to add author data

This can be addressed after launch

**Comment by karenhanson** [comment]
See also #528

**Comment by Rytiggy** [comment]
This ticket is estimated around 1 day of work. Most of the issues here relate to alpaca.js default settings so this issue will be resolved by altering alpaca js defaults.

**Comment by htpvu** [comment]
new requirements: 
For submission using DOI, metadata form need to be not-editable to prevent the metadata from being out of sync with doi metadata

For submission without DOI, user need to be able to add author information.

**Comment by karenhanson** [comment]
@Rytiggy just for some context - when we realized we couldn't fix it in time for launch, @jabrah did this PR to remove the code completely until we could fix it properly: https://github.com/OA-PASS/pass-ember/pull/661
So the code needs to be added back in, and then these bugs fixed.

**Comment by htpvu** [comment]
verified on rev. 3183c0c4
