### ISSUE TITLE
The uploading submission spinner should prevent clicks to other pages until it is finished

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#666]
It is possible to go to the last stage of the submission, hit the button (you see the spinner for uploading files etc), and then click to another page before it is finished e.g. `Grants`.  Currently when you do this an empty alert box appears and the submission is lost. The loading spinner should freeze other page functions or float over the page until it is complete.

**Comment by Rytiggy** [comment]
This is estimated around 2 hours of work, it should be adding an overlay to the page to prevent clicking.

**Comment by htpvu** [comment]
verified on rev. 3183c0c4
