### ISSUE TITLE
Update shib docker set up for pass-ember codebase

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#698]
@cameronblandford I think you're held up by this issue anyways, so i'm creating this ticket to account for your effort. We'll catch up tomorrow at 10am

**Comment by karenhanson** [comment]
@htpvu  Once ACL change to allow all users to read grants is available, this will solve 403 errors. We will need to point to add authz back in and update fcrepo and assets image versions so that it is possible to test with the ACLs enabled
