### ISSUE TITLE
When using no DOI, blank author rows are saved in Submission

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#704]
If you leave blank authors, it saves them as empty.  It would be good if they were removed either once you leave the metadata form, or if it's easier, when the Submission is saved.

![image](https://user-images.githubusercontent.com/4070836/43604765-9851087e-9664-11e8-8f00-2672e4244c35.png)

**Comment by htpvu** [comment]
verified on rev. 3183c0c4
