### ISSUE TITLE
Mistakenly shown the 404 Wizard when viewing a Submission summary

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/pass-ember#705]
I performed a submission on the demo instance, `f78c434e`.

I get to the "Thanks for submitting!" page, and it advertises two links: a link to see the detailed summary of the submission (https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F9d%2F17%2F8a%2F76%2F9d178a76-df73-4719-b526-f33db1b74602) and a link to list all the submissions in my account (https://demo.pass.library.jhu.edu/app/submissions).  The latter link works fine.  The former link briefly displays the submission summary, but then I get the 404 wizard.

After seeing the 404 Wizard on the summary detail page, subsequent visits to that page brought the wizard up immediately without showing the submission detail.  But if I navigated to the submission listing page, then back to the summary detail page, the behavior would repeat itself: I'd see the submission detail briefly, before being shown the 404 wizard.

I turned on developer tools to capture what was going on, and the problem went away.  So maybe a caching issue?  I was using Chrome not in incognito mode. 

Other people in chat today didn't observe this behavior.

**Comment by karenhanson** [comment]
This may be related to this issue: https://github.com/OA-PASS/pass-ember/issues/678
This is difficult to replicate, but seemed to be related to larger files or multiple files. 

The 404 behavior is cached after the first time you see it, so even though the page that produced it in the first place may no longer produce a 404 in the network log, the submission will keep showing 404 page until you clear cache or open a new incognito session.
