### ISSUE TITLE
Basic Step: Add buttons to page ask who you are submitting on behalf for.

### ISSUE THREAD

**Issue by Rytiggy** [OA-PASS/pass-ember#726]
Add lookup for user email if proxy 
This will include the new section for proxy submitter to look up user and all of the associated behavior as described in the mockups.

https://docs.google.com/presentation/d/165I0caR24QhM9fzwJVtiL4Hzyj0cIKWQf_F0lXC7p7k/edit#slide=id.p

- UI elements to inform and ask the user if this new submission is for yourself or on behalf of another. (1d)
     - If User selects “for someone else”, ask for more information
     - Needs to search for users by name or JHED ID
          - Use autocomplete service? On what fields would the search be done - would require re-indexing users to include a new _suggest autocomplete field
          - Standard search - recommend searching on displayName, as firstName and lastName are indexed as keyword
               - “institutionalId” is already indexed as keyword, so a user would have to enter the complete ID before a match would show
- OR link the submission by email - No integration work, just need to save email alongside Submission obj. No extra time, once the model is settled

**Comment by htpvu** [comment]
@cameronblandford as soon as it is possibly please run the UI layout by me before digging deep into the implementation.

**Comment by htpvu** [comment]
0.5 day left
