### ISSUE TITLE
Grant Page: show grants for user you are submitting on behalf for.

### ISSUE THREAD

**Issue by Rytiggy** [OA-PASS/pass-ember#727]
As long as permissions are set correctly so that a proxy submitter is able to view the other user’s grants, this UI element would simply search for Grants to display based off the user’s choice in the previous step. Requires changes to search query (possibly half day playing with search query):
- If the submission is for self: show own grants
- If the submission is for another user: show other user’s grants
- If the only email was given, user should be able to search for grant with text search using grant number or grant name.
(grants are technically available for all to read)

Duplicate Submission handling is descoped from this work. saved for the next release.

**Comment by htpvu** [comment]
@Rytiggy i updated the comment above. no duplicate submission handling needed at this point, but may have to spend sometime dealing with grant search.
