### ISSUE TITLE
 Review: Show proxy submitters names and name of who they are submitting for.

### ISSUE THREAD

**Issue by Rytiggy** [OA-PASS/pass-ember#729]
Save the proxy submitter in the metadata when user clicks submit/request approval, a submissionEvent object needs to be created along with the submission object. 
- Display current user name as Preparer if proxy submitter
- Proxy submitter: button will show “Request Approval” : set submission.submissionStatus = approval-requested or approval-requested-newuser (if the approver was only identified by email and does not yet exist in the system)
- Auth Submitter: button will show “Submit” : Set submission.submissionStatus = submitted, submissionEvent.eventType=submitted
- Add ability to add comments prior to submission - separate components, display comments, add new comment. Comments are to be captured in the associated submissionEvent object.

See this section of the model update document for example of mappings information in the `submission` and `submissionEvent` objects: https://docs.google.com/document/d/1TdI5U9rZAYpLTywKFhNT5D8as8_Lrg12LNV8qHSe130/edit?ts=5b8ece71#heading=h.b156bz7bhwjm

Some information required in submissionEvent will need “special” calculation as described in LinkService Design doc https://docs.google.com/document/d/11tlJC8KwQ9e5C3pu3rARtxmVJz6lUJB865fm1JAHV7U/edit

**Comment by htpvu** [comment]
@Rytiggy I updated this ticket information about the objects that needs to be created when user click submit.  or Request approval. Please be sure to consult the linked documents for specific about how to populate the new objects with required information.

**Comment by Rytiggy** [comment]
I estimate this to be a 1 - 1.5-day task accounting for disruptions.

**Comment by htpvu** [comment]
SubmissionEvent with types `approval-requested-newuser`, `approval-requested` and `changes-requested` should have link value that point to the specific submission's details page with comment section displayed. 

We're not sending submitted notification at this time, but on the even of "submitted", link should also points to the submission details page.
