### ISSUE TITLE
Scan the app for vulnerabilities

### ISSUE THREAD

**Issue by birkland** [OA-PASS/pass-ember#73]
JHU has a security-scanning thingy for production apps.   `pass-ember` is an entirely client-side application at the moment (i.e. it's an html file, which links to a javascript file.  That's it.  it doesn't connect to any services yet).  The scanner does check javascript, so it might be able to let us know if there early on if there are any looming problems (i.e. one of the billions of little js dependencies has a known vulnerability).  

Don't know how smart it is - maybe the opaque minified and concatenated js blob Ember spits out is impenetrable by the scanner, resulting in automatic "OK".  

It may be worth a try early on just to see if we're OK, or have problems to address.

**Comment by htpvu** [comment]
Not an issue with our AWS set up.
