### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by Rytiggy** [OA-PASS/pass-ember#730]
## Plan 
- create commenting component 
- add component to submission detail and review page:
- create a sidebar that shows comments through proxy workflow  review 

Notes: 
Captured comments will be part of the SubmissionEvent 

<i><small>~2 days</small></i>

**Comment by htpvu** [comment]
This ticket should also account for the UI form needed to capture user's comment on the submission review page.

**Comment by htpvu** [comment]
1 day left
