### ISSUE TITLE
Submission Details: Show all comments associated with the submission ordered by time

### ISSUE THREAD

**Issue by Rytiggy** [OA-PASS/pass-ember#732]
Add buttons to bottom for new interactions depending on who is interacting with submission. 

Include the legal agreement popup, should account for multiple legal agreements 

- Show a status-dependent message
   - Proxy submitter: “This submission requires additional edits. See approvers comments below”
   - Approver: “This submission requires review and approval.”
- Display data: Preparer and Submitter
   - Do we display both if they are the same person (submission done for self)? - Display both as the same person in the case of self submission. (Hanh)
- New section: Comments - should be able to reuse components developed for Submission Review step
   - Display all comments attached to the submission in order by date/time
   - Add ability to attach new comments to the submission
- New buttons at bottom:
   - Proxy:
       - “Edit” button that will launch into Submission workflow to edit submission data
   - Approver:
       - “Reject” button - spike submission forever. Set `submission.submissionStatus = cancelled`. When user reject a submission, he/she will be reqquired to provide a comment about that decision. (Hanh)
       - “Send back to preparer” - request changes by preparer for re-approval. Set `submission.submissionStatus = changes-required` . Comments are required in this case as well (Hanh)
      - “Edit” - same as the proxy edit button
      - “Approve” - send approval

**Comment by htpvu** [comment]
@Rytiggy I updated the comments with my notes.
