### ISSUE TITLE
Don't keep state in controllers

### ISSUE THREAD

**Issue by birkland** [OA-PASS/pass-ember#74]
Right now, controllers are used to hold a list of "newly created objects that are supposed to be linked to the submission upon save, or rolled back upon cancel".  This was fast to write, but dangerous as controllers are singletons.  

Maybe use a component instead.  That way cleanup can be tied to the component lifecycle in case the user "navigated away" without saving or cancelling.

Or maybe don't keep an explicit list of new objects at all and somehow use ember-data to reason about links to objects that haven't been committed.

**Comment by htpvu** [comment]
This ticket may be out of date after the UI code update.
