### ISSUE TITLE
Craft a search query to be used in looking up user for proxy submission 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#743]
it should be possible to search for users by first name, last name, email address, jhed id

As discussed in meeting between Mark, Karen, Hanh and Sayeed, which resulted in the closing of cards 
https://github.com/OA-PASS/general-issues/issues/38 
https://github.com/OA-PASS/pass-indexer/issues/16

**Comment by markpatton** [comment]
First draft here: https://docs.google.com/document/d/15hfUu4jzdJdvgqjQgHAkF2ho-jEts-VbOSH8vElP-wg/edit

**Comment by htpvu** [comment]
Done with query in this PR https://github.com/OA-PASS/pass-indexer/pull/20
