### ISSUE TITLE
Implement a  popup that display the page-able result of a user search 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#744]
when a submission preparer performs a user search to submit a submisison on behalf of, he/she should be shown a pop up with the search result. The search and pop up should have the following characteristics:
- users should be searchable by firstname, lastname, display name, email and jhed id (see @markpatton and his ticket https://github.com/OA-PASS/pass-ember/issues/743 for assistant) 
- result of search should be displayed within the popup and should be page-able
- Each result row should display, User's `firstname lastname email@address`
- each user's name should be hyperlinked, which when clicked will *select* that user and return the preparer to the submission workflow

**Comment by cameronblandford** [comment]
## Steps
- [ ] add link to open popup [0h5m]
- [ ] add basic popup [0h10m]
- [ ] add search window and results window [0h30m]
- [ ] add search functionality [0h30m]
- [ ] add pagination to results window [0h30m]
- [ ] add select functionality [0h30m]
- [ ] test [0h30m]
- [ ] debug [1h0m]

**Comment by markpatton** [comment]
Here is the updated query. Note that we also search middleName, because why not. As before the filter statement should be removed because it is added by Store.query.

```
curl 'http://localhost:9200/test/_search?pretty' -H 'Content-Type: application/json; charset=UTF-8' --data-binary '
{
  "query": {
    "bool" : {
      "filter": {
        "term" : { "@type" : "User" }        
      },
      "should" : [
        { "multi_match" : {"query" : "choudhury, sayeed", "fields" : [ "firstName", "middleName", "lastName", "displayName" ] } },
        { "term" : { "email" : "choudhury, sayeed" } }
      ],
      "minimum_should_match" : 1
    }
  }
}
'
```

**Comment by karenhanson** [comment]
This is essentially done, but there are a few issues with the modal that have been documented in separate issues (#770, #761). Closing this.
