### ISSUE TITLE
Remove old submission status calculation and use new submissionStatus field

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#748]
* remove submission status calculation from `/submissions/` and `/grants/{uri}`
* add new `submissionStatus` field instead
* make sure you can now use it to sort correctly (this will deal with issue #685)
* update the color/status mapping according to the table below

|enum 		|display  		|tooltip |color |
|------------- | ------------- | ------------- |----------|
|`manuscript-expected`  |manuscript expected |A manuscript is required to complete this submission |blue |
|`approval-requested` |approval requested |This submission was been prepared on behalf of the designated submitter and is awaiting approval before being submitted |blue |
|`changes-requested` |changes requested |The designated submitter has requested changes to this submission |blue |
|`cancelled` |cancelled |This submission has been cancelled by the designated submitter |black |
|`submitted` |submitted |The submission was successfully created. PASS will deposit this work into the target repositories and provide a link and feedback where available. |green |
|`needs-attention` |needs attention |PASS has delivered the submission, but one or more repositories have indicated that there may be a need for further action before the submission is complete. Click here for more details |red |
|`complete` |complete |The Submission was accepted by all target repositories and is either pending publication or already published |green |

**Comment by htpvu** [comment]
I think the `needs attention` color should be `yellow`.

I think the wording on the `manuscript expected` should probably be changed, it need smore information i think. Letme think more about it. 

The rest looks good.

**Comment by karenhanson** [comment]
@htpvu actually the text on the current PASS site is more detailed, we could leave it at that:
"Your funder is aware of this publication and is expecting the deposit of your manuscript"
Will switch to yellow

**Comment by htpvu** [comment]
@karenhanson that sounds good.
