### ISSUE TITLE
Update label for button in review page

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#764]
<img width="1057" alt="screen shot 2018-11-02 at 3 23 19 pm" src="https://user-images.githubusercontent.com/11050142/47938505-a8148300-deba-11e8-8b17-1fa99442a520.png">

Shen a proxy submission is prepared. at the end of the workflow, the buttons should say "Request Approval" rather than "Submit" as it's shown in the screenshot

**Comment by karenhanson** [comment]
closed by #766
