### ISSUE TITLE
Document submissions metadata blob

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#771]
Document its structures, fields, format of fields so code interacting with that blob know how to interpret it.

**Comment by htpvu** [comment]
@karenhanson Could you link to the document you created for this. I think this could be closed. we should wait until the design work for the CMF to be done before deciding how much of the blob documentation to be formalized in the README page with the rest of the models.

**Comment by karenhanson** [comment]
Here is the document describing the metadata blob:
https://docs.google.com/document/d/1NO52smr8Uy2HNTM3Lk1RFJXjS5bV6i4ZsNshUiLZMAo
