### ISSUE TITLE
Navigating from Grants to Basics tab resets submitter ID

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#774]
The grants dropdown disappears as if no submitter user.id is set when performing the following steps:
1) create a new submission on behalf of myself
2) next to grants, select grants
3) click the Basics workflow tab (not the back button)
4) click the Grants workflow tab. The grants are still assigned but the dropdown list is missing as it is when you prepare on behalf of a new user. It seems like the submitter value has been zeroed out.

**Comment by karenhanson** [comment]
Wondering if this is related to #747, might be worth seeing if both can be done at the same time.

**Comment by htpvu** [comment]
closed by #778
