### ISSUE TITLE
Fix the use of external-submissions in submission metadata

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#775]
State table for external-submissions in submission metadata: https://docs.google.com/spreadsheets/d/1E0tdwizg0FwIBWegKQpJVahh1TFByksBkiSIlbsQevs/edit#gid=0

**Comment by markpatton** [comment]
When a user prepares a submission on behalf of someone else, the external-submissions field should not be populated.
When a user approves a submission on their behalf from someone else or submits on their own behalf, the external-submissions field should be populated.

**Comment by htpvu** [comment]
Closed by https://github.com/OA-PASS/pass-ember/pull/803
