### ISSUE TITLE
The `link` field is not set on SubmissionEvents

### ISSUE THREAD

**Issue by birkland** [OA-PASS/pass-ember#776]
At present, Ember only populates the `link` field of SubmissionEvents for new users.  However, notification-services expects the `link` to be present in all situations where it might send an e-mail to a user to check on a particular submission.  So at a minimum, it should be set for submissionEvents:
* `approval-requested-newuser`
* `approval-requested`
* `changes-requested`

In fact, it would be ideal to include it on _every_ submissionEvent.

**Comment by markpatton** [comment]
Should link be set to a link to the submission details page for every event type?

**Comment by birkland** [comment]
@markpatton Probably, yes.

**Comment by htpvu** [comment]
Closed by #777
