### ISSUE TITLE
Update About page in static/html & produce new static-html image

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#827]
Old text: `PASS was created by the Sheridan Libraries at Johns Hopkins University, in collaboration with 221B, MIT Libraries and the Harvard University Office for Scholarly Communication`

New text: `PASS was created by the Sheridan Libraries at Johns Hopkins University, in collaboration with the Harvard University Office for Scholarly Communication, the MIT Libraries, and with inspiration from Jeff Spies, formerly of the Center for Open Science.`

**Comment by karenhanson** [comment]
Closed by https://github.com/OA-PASS/pass-docker/pull/173
