### ISSUE TITLE
Update the grant selection page in submission details with new style and layout

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#830]
- [x] (1) number of grants is too big and should align left or right since nothing on the site is aligned center
- [x] (2) number of grants shouldn't be displayed anyway if less than 10.
- [x] (3) bottom table is indented top is not
- [x] (4) funder really needs a min width, it forces the table to be more spaced out than necessary and splits words like "aeronautics"
- [x] (5) the grey highlight color on rows is too dark and little obnoxious, i would go for a lighter grey
- [x] (6) I'm wondering if the back/next buttons should be duplicated under grants added to submission (edited)
- [x] (7) The table at the top should include the date like this `ANALYSIS OF BLAH BLAH (12/12/2016-12/12/2018)`
- [x] (8) Add date range to project name on bottom to help with spacing? 
- [x] (9) reword top to say "Please select grant(s)/award(s) that funded this work." take out the second "Please select grants that should be associated with this submission.", reword "If you could not find your grant in the below dropdown list" -> "If your grant is not listed, please contact us"
- [x] (10) make subheadings smaller
- [x] (11) link grants in bottom table same as top table

**Comment by karenhanson** [comment]
Closed by PR #832
