### ISSUE TITLE
Travis fails with "failed to deploy" once PR merged

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#842]
PRs are passing Travis tests, but once merged they fail with the following message:
```
Please add SURGE_TOKEN in Travis settings (get your token with 'surge token')
Preparing deploy
failed to deploy
```
https://travis-ci.org/OA-PASS/pass-ember:

**Comment by jabrah** [comment]
We should update Travis config `.travis.yml` to get rid of `before_deploy` and `deploy` steps. Those steps were hold overs from prior work done by contractors, where they automatically deployed builds to their own servers for informal demos using a service https://surge.sh/

**Comment by jabrah** [comment]
Closed by https://github.com/OA-PASS/pass-ember/pull/916
