### ISSUE TITLE
Submission workflow's repositories list is not properly populated

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#85]
Tied to this is the metadata forms - if a target repository is not identified, then no metadata forms would appears <-- this is consistent, probably a good thing because metadata forms are repositories driven. 

I've encountered issue with repositories list not properly populated based on policies many ways. Below is one of the ways:

1. from Submissions table, click "New Submission"
2. Enter DOI, select a method A journal (ACS Medicinal Chemistry...) 
3. Enter NIH award number (one starts with R)
4. Advance to "compliance" screen, observe that the app states that the journal is method a journal
5. Advance to "repositories" screen, observe that there's no repo added
6. go back to "award" screen, add a grant from NSF (one starts with a number) 
7. Observe NSF policy showing in the "Compliance" screen
8. Advance to the "repositories" screen, observe that no repositories show up 
9. Advancing to the Metadata section will show no metadata screen. 

Side note: I think user should be offered an option to quit the whole thing between step 4&5 above.

**Comment by htpvu** [comment]
@birkland I couldn't attach the video on this ticket, but I sent you the screencast in slack

**Comment by birkland** [comment]
@htpvu Hm.  When I read through those steps (without seeing the video), it _worked_.  I'll send you the video on Slack.  Then I saw your video.  The key difference was steep (6).  I navigated directly to 'awards' through the side menu.  You used the back buttons.

**Comment by htpvu** [comment]
This ticket is out of date given PASS UI new code base.
