### ISSUE TITLE
Automatic creation of a Journal through Ember results in duplicate records

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-ember#857]
May or may not be related to #856 - it is unclear if this error is making the issue worse.

When you enter a DOI for a Journal that is not in the Fedora repository, Ember generates a new record for that Journal. Currently, this process results in the creation of 2 or even 3 copies of the Journal record. This is likely caused by the fact that the DOI validation process is triggered every time there is an action on the DOI form field, and that process initiates journal creation - in other words multiple actions may be triggering multiple DOI validation calls before the journal is discoverable in ElasticSearch. In light of this issue and the issue documented in #856, a general overhaul of how missing journal information is populated may be warranted.

For convenience, here are several DOIs that are from Journals not currently in our assets instance.
10.1177/1748048507072777 
10.1017/S153759270909080X 
10.1177/1541344605276792

**Comment by markpatton** [comment]
Journals are no longer created by pass-ember.
