### ISSUE TITLE
Move the signing of deposit agreement to the end of the workflow

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#874]
When users clicks submit, the deposit agreement popups up asking him/her to check a box. 

mimic and reuse as much as possible from the proxy submission workflow (where the approver submits the submission).

**Comment by markpatton** [comment]
When creating a new submission, on the new/metadata step, there is a checkbox for a deposit agreement to JScholarship. The goal of this ticket is to remove that step and instead have a popup when submit is clicked? What about the author entry which is the only other part of the new/metadata step?

**Comment by htpvu** [comment]
@markpatton, yes the goal of this ticket is remove the deposit agreement text and its associated checkbox from the metadata step. add a popup when submit is clicked. This ticket is only concerned with the agreement, and no other data.

**Comment by markpatton** [comment]
There is different logic for agreementText in app/controllers/submissions/detail.js. A good outcome of this issue would be to normalize the handling of agreementText, possibly with a service.

**Comment by htpvu** [comment]
@markpatton that sounds great. please feel free to improve the overall state of the code involving deposit agreement. From the user's view, I prefer the way it's handled at the end of the Proxy Submission being approved
