### ISSUE TITLE
Save in progress submissions between new submission workflow steps

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#887]
* [x] Explicitly save the incomplete Submission object between workflow steps
  * Both forward and back directions in the workflow?
  * `submission.submitted` must be `false` until the user clicks the final Submit button in the workflow review step. The workflow review step sets this to `true`
* ~~[ ] Change submissions view to filter out in progress submissions?~~
* [x] Submissions table must correctly display in-progress submissions
  * Allow user to edit or remove them
* [x] Test
* [ ] Test

1d

**Comment by jabrah** [comment]
Modifications required to get the Submissions/Submission Details pages to work nicely are a bit more complicated than initially thought. We can take this opportunity to allow users to resume or destroy "draft" submissions, allowing them to start a submission, then finish it at another time or another computer. A few things need to happen to support this:

* [ ] Extend the `submission-handler` to delete records
* [ ] Add new 'Action' in the last column of the Submissions table
* [ ] Add this action to Submission Details page
* [ ] Submissions table and Submission Details page need to be updated to accommodate incomplete or missing data
* [ ] Extend submission status logic to handle these Draft submissions
* [ ] Add an explicit ‘Abort’ feature to the submission workflow that will remove the “draft” submission
  * [ ] Confirmation box on Abort?

**Comment by markpatton** [comment]
If we want to actually delete the Fedora object corresponding to a "draft" submission, we have to think about other objects which reference a draft submission or are created along with a draft submission.

**Comment by jabrah** [comment]
Need to modify the way Publication objects are saved during the workflow. It is currently saved during the final review step. However, in order to initialize draft submissions in the workflow, we need to be able to link and load a publication object. The Publication object should be saved after the publication information has been entered - during the first step (`workflow-basics`). This will involve making several changes.

**Comment by jabrah** [comment]
Note for Abort button:

The nicer looking place to put this button in the submission workflow requires adding the button to all submission workflow steps. The 'abort' action will need to be bubbled from `controller/submissions/new` up to each workflow component.

Example:

* `controllers/submissions/new` defines the base action `abort`
* `controllers/submissions/new/basics`
  * Inject a reference to the `submissions/new` controller: `Ember.inject.controller('submissions.new')`
  * Define `abort` action that explicitly sends `abort` to the injected controller 
* `templates/submissions/new/basics` add `abort` action to the instantiation of `workflow-basics` component
* `components/workflow-basics` add new `cancel` action
  * When this action is invoked, call `sendAction('abort')` to push the action back down to the `basics` controller
* `templates/components/workflow-basics` finally add the new button with the reference `{{action 'cancel'}}`

**Comment by jabrah** [comment]
Will close this and open tickets with remaining issues that will be addressed later
