### ISSUE TITLE
Update ember code to pass the DOI CrossRef response to the journal service to retrieve journal object for the submission workflow

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#899]

**Comment by jabrah** [comment]
Looks like metadata handling will have to be updated (again). Basically, I think this like needs to be taken out of the `doi` service (https://github.com/OA-PASS/pass-ember/blob/routes-refactoring/app/services/doi.js#L46).

This will be more of a pain than expected :( It's possible we can hack things by:

* Remove the processing step from the URL above
* Call `doi#resolveDOI` from `workflow-basics` component
  * Save raw data and a copy in separate variables, calling `doi#_processRawDoi` to post-process the copy
* Use unprocessed DOI data when calling journal service, continue with other code in `workflow-basics` using processed copy

OR we can investigate the design of the journal service

**Comment by htpvu** [comment]
This ticket includes the work to remove code to look up NLMTA from the ember code base.
