### ISSUE TITLE
User service is poorly written and has some odd behavior.

### ISSUE THREAD

**Issue by markpatton** [OA-PASS/pass-ember#902]
The service mutates a class variable for the service url with a userToken if provided. Multiple calls with the userToken will corrupt the url. The call to this.get with multiple parameters is also suspect.

In addition, if user token has a special character, then user login will fail.

The service also needs to be documented.

**Comment by birkland** [comment]
The user token is base32 encoded, so urlencoding it will be a no-op.  Urlencoding will protect against the case where some time in the future we change the token spec in such a way that the resulting token contains characters that need urlencoding.

**Comment by markpatton** [comment]
Need to figure out exact behavior of passing a userToken to service. If a userToken is passed, should subsequent calls without a userToken send that userToken? If so, better to just make userToken a parameter on the service.

**Comment by markpatton** [comment]
A userToken once passed to the service should not be "saved".
