### ISSUE TITLE
Update handling of web-link repositories in the UI

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#924]
Update code base to keep weblink repositories in the submission's repo list and NOT in the metadata blob, in which it will fail metadata schema validation

**Comment by jabrah** [comment]
Changes required:

* [ ] `components/workflow-metadata`
* [ ] `components/workflow-review`
* [ ] `service/metadata-blob`
* [ ] `service/submission-handler`
* [ ] `submissions/detail`
  * [ ] controller
  * [ ] template
