### ISSUE TITLE
Metadata displays show internal information

### ISSUE THREAD

**Issue by markpatton** [OA-PASS/pass-ember#927]
In the workflow-review component and submission details page, metadata such as $schema is displayed which should probably be concealed. We should determine what metadata should be displayed and do so consistenly.

**Comment by markpatton** [comment]
Should pull the labels from the properties in the schemas

**Comment by htpvu** [comment]
For complex objects, namely, authors and issns, we will display them as follow:
- ISSN: xxxx-xxxx(pubtype)
- Author: full name(ORCID) 

Whitelist for fields to be displayed (unless they are empty):
- agreements
- abstract
- authors
- DOI
- Embargo End date
- NLMTA
- Journal Title
- Journal title short
- Issue 
- ISSNs
- Publisher
- Publication Date
- Title
- Volume

**Comment by markpatton** [comment]
Should also having a fixed order of display.
