### ISSUE TITLE
Metadata form layout tweak #1

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#938]
![Screenshot from 2019-05-07 12-50-55](https://user-images.githubusercontent.com/11050142/58279160-aaadcb80-7d6b-11e9-84da-47f1013bb7f1.png)

**Comment by jabrah** [comment]
I'm pretty sure the `<p>` tags in the Abstract come directly from the DOI data

**Comment by jabrah** [comment]
Should I make similar changes to the ISSN related fields?

**Comment by htpvu** [comment]
![Screenshot from 2019-05-07 12-50-49](https://user-images.githubusercontent.com/11050142/58502680-0229ae00-8155-11e9-944d-c56b8763506c.png)

@jabrah please see if the layout of the pubtype layout could be addressed?

**Comment by jabrah** [comment]
I can simply have the button toolbar appear only when the user hovers over the row.

Having the publication type options display horizontally is also possible.

Should I also get rid of the "None" option?
