### ISSUE TITLE
Make sure that if fields in the metadata form is populated by Cross ref look up, they are not editable in anyway 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#939]
This applies to all the metadata forms.

**Comment by jabrah** [comment]
Current solution potentially leaves Alpaca in an invalid state? The following warnings appear when the forms are rendered.

```
alpaca.min.js:1 The field (id=alpaca5, title=Array Field, path=/authors) is invalid and also read-only
alpaca.min.js:1 The field (id=alpaca6, title=Array Field, path=/issns) is invalid and also read-only
```

The metadata seems to be OK on the submission object and it doesn't seem to effect how the forms are rendered.
