### ISSUE TITLE
Journal title did not get populate on the form when user tries to "Finish" a submission

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#957]
<img width="619" alt="Screen Shot 2019-06-14 at 10 25 33 AM" src="https://user-images.githubusercontent.com/11050142/59534684-07109080-8ebd-11e9-8722-08c404ca7487.png">

Steps:
- logs on as nih-user
- go to Submissions screen
- Click Finish Submission on the submission with status "Manuscript Expected" 
- Enters the submisison workflow, observe that the DOI and TItle field has been prepopulated but the journal title field has not.

**Comment by jabrah** [comment]
When I ran `pass-ember`, the test submission that can be "Finished" did not have a Journal attached to its Publication, so the workflow was unable to populate the journal field. The journal field is populated correctly when editing a draft submission.
