### ISSUE TITLE
ORCIDs are not required

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#958]
<img width="621" alt="Screen Shot 2019-06-14 at 10 30 19 AM" src="https://user-images.githubusercontent.com/11050142/59535066-ed237d80-8ebd-11e9-8f28-cffdfaafd2be.png">
On the J10P metadata screen, ORCIDs are said to be required. but they are not.

**Comment by markpatton** [comment]
The issue may be that they are not marked as required by the schema. The authors array is marked required, but not author and orcid values.

**Comment by birkland** [comment]
How does the 'required' text make it to the screen?  Is inferred by analyzing the schema, out-of-band information that is baked into the Ember codebase, or something else?  

I believe the theory behind using schemas in the first place was that they'd be the sole source of Truth for this sort of thing.

**Comment by markpatton** [comment]
I think the display is all alpaca.

**Comment by markpatton** [comment]
Ok. So this has entirely to due with the json schema. See https://github.com/OA-PASS/metadata-schemas/pull/30 for a fix.
