### ISSUE TITLE
Layout issues with metadata form: ISSN type need spacing between radio button and text

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#960]
<img width="186" alt="Screen Shot 2019-06-18 at 9 58 43 AM" src="https://user-images.githubusercontent.com/11050142/59690673-c4e29a00-91af-11e9-901c-310f421df31a.png">

**Comment by jabrah** [comment]
Closed by https://github.com/OA-PASS/pass-ember/pull/988
