### ISSUE TITLE
`publicationDate` does not make it into the metadata blob

### ISSUE THREAD

**Issue by jabrah** [OA-PASS/pass-ember#964]
There is a "Publication Date" field in our metadata schema, but no such date makes it from the Crossref blob we get from the DOI into the metadata forms - thus this field doesn't make it into the submission's metadata blob.

`doi#doiToMetadata` has the mapping which needs to be updated once we know which Crossref field matches the `publicationDate`

**Comment by jabrah** [comment]
There are several dates to play with that Crossref returns, see https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md#work for some light bedtime reading describing the properties of the Crossref data.

Some good possible candidates are (though other dates exist):

* **`issued`** (this reduces two dates - takes the earliest of `published-print` or `published-online`)
* `published-print`
* `published-online`

**Comment by htpvu** [comment]
Yup, I think `issued` is the field to use here.

**Comment by jabrah** [comment]
`publicationDate` currently has its format set to `date`, meaning the schema will have strict formatting validation. `yyyy-mm-dd` will validate. 

Question for @emetsger : is it safe to make this a `string` value with no formatting requirements? i.e. will this break J10P in any way? If so, I can modify the schema and do a simple mapping from Crossref data.

**Comment by htpvu** [comment]
It should be set to date. Publication dates are unpredictable. At times, they are something like “Fall 2019” which wouldn’t validate

Hanh Vu
Project Manager
Sheridan Libraries, Johns Hopkins University

________________________________

**Comment by birkland** [comment]
@htpvu does that mean that values like "Fall 2019" and "2018" should be discarded, so as to avoid a schema validation error?

**Comment by htpvu** [comment]
It means the schema validation should not validate this field as a date but rather as a string

Hanh Vu
Project Manager
Sheridan Libraries, Johns Hopkins University

________________________________
