### ISSUE TITLE
Update ui code base to use the newly implemented functionality ot schema service

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/pass-ember#968]
Schema service is being updated to return a compacted metadata schema when asked. update Ui to use this feature. 

compacted metadata schema is one made out of combining all of the mdata schema applicable in a workflow.

**Comment by jabrah** [comment]
This requires a minor update to the `metadata-schema` service in the Ember codebase:
* Should default to adding URL query parameter: `?merged=true`
* If initial request fails (with which error?), retry the request _without_ the query parameter to get the non-merged list of schema

I also observed some odd behavior from JSON schema validation in the client, will have to investigate.
