### ISSUE TITLE
Effective policies on the Fedora Submission are not updated when skipping through the workflow

### ISSUE THREAD

**Issue by emetsger** [OA-PASS/pass-ember#995]
To reproduce:

1. Login as `nih-user`, start a submission with a DOI (e.g. 10.1016/j.neuron.2015.04.009).  Click `Next` to go to `Grants`
2. Pick an NIH grant to associate with the Submission (e.g. award number `R01EY012124`)
3. Click `Next` to go to `Policies`
4. Click `Next` to go to `Repositories`

At this juncture, the Fedora Submission has two `Submission.effectivePolicies`, one for J10P, one for PubMed, as expected.

5. Click on `Grants` (do not click `Back`.  Skip back 2 steps by clicking on `Grants`).
6. (Note that if you refresh the Fedora Submission, it now has two `Submission.repositories`)
7. In Ember, remove the single NIH grant.
8. Then skip forward in the workflow by clicking `Repositories`.  (do not click `Next`. Skip steps by clicking on `Repositories`)
9. You receive the "Something went wrong" message.
10. Refresh the Fedora Submission, and observe that the `Grant` is gone, but the two `Submission.repositories` remain, as do the two `Submission.effectivePolicies`.  This seems incorrect.  The NIH `Grant` was removed, so the policy reference should be removed from `Submission.effectivePolicies`, and the `Repository` for the policy should also be removed.

The "Something went wrong" comes from invoking the Policy service on the `Repositories` step.  Presumably the Policy service calculates the  applicable policies for the submission according to the policy rules, and discovers that the NIH policy attached to the Submission is present in error (because there's no link from the Submission to the Grant -> Funder -> Policy).

Affects pass-docker f2361f2 and pass-ember 790edea

**Comment by jabrah** [comment]
The logic for adding repositories and calculating effective policies is currently isolated in each respective workflow step, so I can see how skipping these steps would result in bad behavior. It was intended that when a user modifies the grant selection, the application would force the user to move through the rest of workflow again by keeping the user from skipping forward.

Hopefully this would be a sufficient fix.
